"""Tests for the canonical proof-certificate JSON Schema.

`schema/proof-cert.schema.json` is the single source of truth for the
`.proof.json` / `.proof-cert.json` contract shared across the Rust producer
(`mumei-core/src/proof_cert.rs`) and the Python consumers in `mumei-agent`
and `mumei-lean`.

These tests guard against the schema drifting away from real compiler output:
committed golden certificates (generated by the Mumei compiler) must validate
against the schema, and the contract enum values must remain stable.
"""
from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "schema" / "proof-cert.schema.json"
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "proof-cert"

# The canonical contract enums. These must match the documented values in
# `mumei-core/src/proof_cert.rs` (module `status`) and the `$defs` enums in the
# schema. Changing a value here is intentional and forces a coordinated update
# of the Rust producer and the Python consumers.
EXPECTED_Z3_CHECK_RESULTS = ["unsat", "sat", "unknown", "skipped", "lean_verified", "timeout", "resource_limit", "spurious_candidate"]
EXPECTED_VERIFICATION_STATUSES = [
    "verified",
    "failed",
    "skipped",
    "trusted",
    "escalation_candidate",
]


def _load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def test_schema_is_a_valid_json_schema():
    schema = _load_schema()
    jsonschema.Draft202012Validator.check_schema(schema)


def test_contract_enums_are_stable():
    defs = _load_schema()["$defs"]
    assert defs["z3CheckResult"]["enum"] == EXPECTED_Z3_CHECK_RESULTS
    assert defs["verificationStatus"]["enum"] == EXPECTED_VERIFICATION_STATUSES


def _fixture_paths() -> list[Path]:
    return sorted(FIXTURE_DIR.glob("*.proof-cert.json"))


def test_golden_fixtures_exist():
    assert _fixture_paths(), f"no golden proof-cert fixtures found under {FIXTURE_DIR}"


@pytest.mark.parametrize("fixture", _fixture_paths(), ids=lambda p: p.name)
def test_golden_fixture_conforms_to_schema(fixture: Path):
    schema = _load_schema()
    instance = json.loads(fixture.read_text(encoding="utf-8"))
    jsonschema.validate(instance, schema)


def test_unknown_status_is_rejected():
    """A non-canonical status value must fail validation (enum guard works)."""
    schema = _load_schema()
    fixture = _fixture_paths()[0]
    instance = json.loads(fixture.read_text(encoding="utf-8"))
    instance["atoms"][0]["status"] = "definitely-not-a-status"
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(instance, schema)


def test_escalation_candidate_atom_is_accepted():
    """An unknown-but-escalated atom (z3 'skipped'/'unknown' + status
    'escalation_candidate') is valid output and must conform."""
    schema = _load_schema()
    fixture = _fixture_paths()[0]
    instance = json.loads(fixture.read_text(encoding="utf-8"))
    atom = instance["atoms"][0]
    atom["z3_check_result"] = "unknown"
    atom["status"] = "escalation_candidate"
    jsonschema.validate(instance, schema)
