use mumei_core::emitter::Emitter;
use mumei_core::hir::lower_atom_to_hir;
use mumei_core::parser::ast::Atom;
use mumei_core::parser::{parse_module_checked, Item};
use mumei_core::verification::ModuleEnv;
use mumei_emit_python::PythonWrapperEmitter;
use mumei_emit_rust::RustWrapperEmitter;
use std::path::Path;

struct WrapperGolden<'a> {
    name: &'a str,
    source: &'a str,
    qualified_name: Option<&'a str>,
    python: &'a str,
    rust: &'a str,
}

fn parsed_atom(source: &str, qualified_name: Option<&str>) -> Atom {
    let items = parse_module_checked(source).unwrap_or_else(|errors| {
        panic!("source should parse: {}", errors.join("\n"));
    });
    let mut atom = items
        .into_iter()
        .find_map(|item| match item {
            Item::Atom(atom) => Some(atom),
            Item::ImplBlock(block) => block.methods.into_iter().next(),
            _ => None,
        })
        .expect("source should contain an atom");
    if let Some(name) = qualified_name {
        atom.name = name.to_string();
    }
    atom
}

fn emit_python(hir: &mumei_core::hir::HirAtom, module_env: &ModuleEnv) -> Vec<u8> {
    PythonWrapperEmitter
        .emit(&hir.emit_view(), Path::new("wrapper"), module_env, &[])
        .expect("Python wrapper should emit")[0]
        .data
        .clone()
}

fn emit_rust(hir: &mumei_core::hir::HirAtom, module_env: &ModuleEnv) -> Vec<u8> {
    RustWrapperEmitter
        .emit(&hir.emit_view(), Path::new("wrapper"), module_env, &[])
        .expect("Rust wrapper should emit")[0]
        .data
        .clone()
}

fn assert_wrapper_golden(case: &WrapperGolden<'_>) {
    let atom = parsed_atom(case.source, case.qualified_name);
    let mut hir = lower_atom_to_hir(&atom);
    if case.name == "rich" {
        assert!(hir.contract.requires_text.ends_with("&& true"));
    }

    let module_env = ModuleEnv::new();
    let python_before = emit_python(&hir, &module_env);
    let rust_before = emit_rust(&hir, &module_env);
    assert_eq!(
        std::str::from_utf8(&python_before).unwrap(),
        case.python,
        "{} Python",
        case.name
    );
    assert_eq!(
        std::str::from_utf8(&rust_before).unwrap(),
        case.rust,
        "{} Rust",
        case.name
    );

    hir.atom = parsed_atom(
        r#"
atom unrelated() -> bool
requires: false;
ensures: false;
body: { false }
"#,
        None,
    );
    assert_eq!(
        emit_python(&hir, &module_env),
        python_before,
        "{} Python AST independence",
        case.name
    );
    assert_eq!(
        emit_rust(&hir, &module_env),
        rust_before,
        "{} Rust AST independence",
        case.name
    );

    if case.name == "defaults" {
        let python = String::from_utf8(python_before).unwrap();
        let rust = String::from_utf8(rust_before).unwrap();
        assert!(!python.lines().any(|line| line.starts_with("    assert ")));
        assert!(!rust.contains("    assert!("));
        assert!(!rust.contains("    debug_assert!("));
    }
}

#[test]
fn parser_backed_wrappers_match_develop_goldens_and_ignore_the_ast() {
    let cases = [
        WrapperGolden {
            name: "rich",
            source: r#"
atom rich_wrapper(
    consume a: i64,
    ref b: i64,
    ref mut c: bool,
    plain,
    enabled: bool
) -> i64
requires: (a >= 0 && b >= 0) && forall(i, 0, a, i >= 0);
ensures: result >= a && enabled == true;
body: { a }
"#,
            qualified_name: None,
            python: r###"# Auto-generated by mumei PythonWrapperEmitter
# FFI glue code — NOT transpiled mumei source.
# This file provides Python wrappers around a compiled mumei binary.

"""
FFI wrapper for verified atom `rich_wrapper`.

Precondition: (a >= 0 && b >= 0) && true
Postcondition: result >= a && enabled == true
"""

import ctypes
import os
from ctypes import c_int64

# Load the compiled mumei binary.
# Adjust the path to your compiled .so/.dll/.dylib as needed.
_LIB_PATH = os.environ.get("MUMEI_LIB_PATH", "./libmumei.so")
_lib = ctypes.CDLL(_LIB_PATH)

_lib.rich_wrapper.argtypes = [c_int64, c_int64, c_int64, c_int64, c_int64]
_lib.rich_wrapper.restype = c_int64

def rich_wrapper(a: int, b: int, c: bool, plain: int, enabled: bool) -> int:
    """Safe wrapper for verified atom `rich_wrapper`.

    Calls into a compiled mumei binary via ctypes FFI.
    Preconditions are checked at runtime via assert.

    Precondition: (a >= 0 && b >= 0) && true
    Postcondition: result >= a && enabled == true
    """
    assert a >= 0 and b >= 0, "precondition violated: (a >= 0 && b >= 0) && true"
    assert all(i >= 0 for i in range(0, a)), "precondition violated: forall(i, 0, a, i >= 0)"
    result = _lib.rich_wrapper(a, b, c, plain, enabled)
    assert result >= a and enabled == True, "postcondition violated: result >= a && enabled == true"
    return result
"###,
            rust: r###"// Auto-generated by mumei RustWrapperEmitter
// FFI glue code — NOT transpiled mumei source.
// This file provides safe Rust wrappers around a compiled mumei binary.

extern "C" {
    fn rich_wrapper(
    a: i64,
    b: i64,
    c: i64,
    plain: i64,
    enabled: i64
    ) -> i64;
}

/// Safe wrapper for the verified `rich_wrapper` atom.
///
/// # Safety
/// Calls into a compiled mumei binary via FFI.
/// Preconditions are checked at runtime via `assert!`.
/// Postconditions are checked via `debug_assert!`.
///
/// # Precondition
/// `(a >= 0 && b >= 0) && true`
///
/// # Postcondition
/// `result >= a && enabled == true`
pub fn rich_wrapper_safe(a: i64, b: i64, c: i64, plain: i64, enabled: i64) -> i64 {
    assert!(a >= 0 && b >= 0, "precondition violated: (a >= 0 && b >= 0) && true");
    assert!(((0)..(a)).all(|i| i >= 0), "precondition violated: forall(i, 0, a, i >= 0)");
    let result = unsafe { rich_wrapper(a, b, c, plain, enabled) };
    debug_assert!(result >= a && (enabled != 0) == true, "postcondition violated: result >= a && enabled == true");
    result
}
"###,
        },
        WrapperGolden {
            name: "qualified",
            source: r##"
impl Vec2 {
atom dot(x: i64, text: i64) -> i64
requires: !(x < 0) || true && false => text == "say \"hi\"";
ensures: result >= 0;
body: { x }
}
"##,
            qualified_name: Some("Vec2::dot"),
            python: r###"# Auto-generated by mumei PythonWrapperEmitter
# FFI glue code — NOT transpiled mumei source.
# This file provides Python wrappers around a compiled mumei binary.

"""
FFI wrapper for verified atom `Vec2::dot`.

Precondition: !(x < 0) || true && false => text == "say \"hi\""
Postcondition: result >= 0
"""

import ctypes
import os
from ctypes import c_int64

# Load the compiled mumei binary.
# Adjust the path to your compiled .so/.dll/.dylib as needed.
_LIB_PATH = os.environ.get("MUMEI_LIB_PATH", "./libmumei.so")
_lib = ctypes.CDLL(_LIB_PATH)

_lib.Vec2_dot.argtypes = [c_int64, c_int64]
_lib.Vec2_dot.restype = c_int64

def Vec2_dot(x: int, text: int) -> int:
    """Safe wrapper for verified atom `Vec2::dot`.

    Calls into a compiled mumei binary via ctypes FFI.
    Preconditions are checked at runtime via assert.

    Precondition: !(x < 0) || true && false => text == "say \"hi\""
    Postcondition: result >= 0
    """
    # mumei: requires not expressible as a Python runtime check; left to verification: !(x < 0) || true && false => text == "say \"hi\""
    result = _lib.Vec2_dot(x, text)
    assert result >= 0, "postcondition violated: result >= 0"
    return result
"###,
            rust: r###"// Auto-generated by mumei RustWrapperEmitter
// FFI glue code — NOT transpiled mumei source.
// This file provides safe Rust wrappers around a compiled mumei binary.

extern "C" {
    fn Vec2_dot(
    x: i64,
    text: i64
    ) -> i64;
}

/// Safe wrapper for the verified `Vec2::dot` atom.
///
/// # Safety
/// Calls into a compiled mumei binary via FFI.
/// Preconditions are checked at runtime via `assert!`.
/// Postconditions are checked via `debug_assert!`.
///
/// # Precondition
/// `!(x < 0) || true && false => text == "say \"hi\""`
///
/// # Postcondition
/// `result >= 0`
pub fn Vec2_dot_safe(x: i64, text: i64) -> i64 {
    // mumei: requires not expressible as a Rust runtime check; left to verification: !(x < 0) || true && false => text == "say \"hi\""
    let result = unsafe { Vec2_dot(x, text) };
    debug_assert!(result >= 0, "postcondition violated: result >= 0");
    result
}
"###,
        },
        WrapperGolden {
            name: "modes",
            source: r#"
atom mode_wrapper(x: i64) -> i64
requires: (x >= 0);
requires: (x < 10);
requires assume: x != 0;
ensures check: result >= 0;
body: { x }
"#,
            qualified_name: None,
            python: r###"# Auto-generated by mumei PythonWrapperEmitter
# FFI glue code — NOT transpiled mumei source.
# This file provides Python wrappers around a compiled mumei binary.

"""
FFI wrapper for verified atom `mode_wrapper`.

Precondition: (((x >= 0)) && ((x < 10))) && (x != 0)
Postcondition: result >= 0
"""

import ctypes
import os
from ctypes import c_int64

# Load the compiled mumei binary.
# Adjust the path to your compiled .so/.dll/.dylib as needed.
_LIB_PATH = os.environ.get("MUMEI_LIB_PATH", "./libmumei.so")
_lib = ctypes.CDLL(_LIB_PATH)

_lib.mode_wrapper.argtypes = [c_int64]
_lib.mode_wrapper.restype = c_int64

def mode_wrapper(x: int) -> int:
    """Safe wrapper for verified atom `mode_wrapper`.

    Calls into a compiled mumei binary via ctypes FFI.
    Preconditions are checked at runtime via assert.

    Precondition: (((x >= 0)) && ((x < 10))) && (x != 0)
    Postcondition: result >= 0
    """
    assert x >= 0 and x < 10 and x != 0, "precondition violated: (((x >= 0)) && ((x < 10))) && (x != 0)"
    result = _lib.mode_wrapper(x)
    assert result >= 0, "postcondition violated: result >= 0"
    return result
"###,
            rust: r###"// Auto-generated by mumei RustWrapperEmitter
// FFI glue code — NOT transpiled mumei source.
// This file provides safe Rust wrappers around a compiled mumei binary.

extern "C" {
    fn mode_wrapper(
    x: i64
    ) -> i64;
}

/// Safe wrapper for the verified `mode_wrapper` atom.
///
/// # Safety
/// Calls into a compiled mumei binary via FFI.
/// Preconditions are checked at runtime via `assert!`.
/// Postconditions are checked via `debug_assert!`.
///
/// # Precondition
/// `(((x >= 0)) && ((x < 10))) && (x != 0)`
///
/// # Postcondition
/// `result >= 0`
pub fn mode_wrapper_safe(x: i64) -> i64 {
    assert!(x >= 0 && x < 10 && x != 0, "precondition violated: (((x >= 0)) && ((x < 10))) && (x != 0)");
    let result = unsafe { mode_wrapper(x) };
    debug_assert!(result >= 0, "postcondition violated: result >= 0");
    result
}
"###,
        },
        WrapperGolden {
            name: "defaults",
            source: r#"
atom default_wrapper(x)
requires: true;
ensures: true;
body: { x }
"#,
            qualified_name: None,
            python: r###"# Auto-generated by mumei PythonWrapperEmitter
# FFI glue code — NOT transpiled mumei source.
# This file provides Python wrappers around a compiled mumei binary.

"""
FFI wrapper for verified atom `default_wrapper`.

"""

import ctypes
import os
from ctypes import c_int64

# Load the compiled mumei binary.
# Adjust the path to your compiled .so/.dll/.dylib as needed.
_LIB_PATH = os.environ.get("MUMEI_LIB_PATH", "./libmumei.so")
_lib = ctypes.CDLL(_LIB_PATH)

_lib.default_wrapper.argtypes = [c_int64]
_lib.default_wrapper.restype = c_int64

def default_wrapper(x: int) -> int:
    """Safe wrapper for verified atom `default_wrapper`.

    Calls into a compiled mumei binary via ctypes FFI.
    Preconditions are checked at runtime via assert.
    """
    result = _lib.default_wrapper(x)
    return result
"###,
            rust: r###"// Auto-generated by mumei RustWrapperEmitter
// FFI glue code — NOT transpiled mumei source.
// This file provides safe Rust wrappers around a compiled mumei binary.

extern "C" {
    fn default_wrapper(
    x: i64
    ) -> i64;
}

/// Safe wrapper for the verified `default_wrapper` atom.
///
/// # Safety
/// Calls into a compiled mumei binary via FFI.
/// Preconditions are checked at runtime via `assert!`.
/// Postconditions are checked via `debug_assert!`.
pub fn default_wrapper_safe(x: i64) -> i64 {
    let result = unsafe { default_wrapper(x) };
    result
}
"###,
        },
    ];

    for case in &cases {
        assert_wrapper_golden(case);
    }
}
