"""Tests for scripts/generate_stdlib_metrics.py.

Covers the history-extraction helpers introduced alongside the History
section of ``docs/STDLIB_METRICS.md``.
"""
from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_PATH = REPO_ROOT / "scripts" / "generate_stdlib_metrics.py"


def _load_module():
    spec = importlib.util.spec_from_file_location(
        "generate_stdlib_metrics",
        SCRIPT_PATH,
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


gsm = _load_module()


SAMPLE_METRICS_MD = """# Mumei std/ Metrics

_Auto-generated by `scripts/generate_stdlib_metrics.py` — 2026-04-22 12:54 UTC_

## Summary

- **Modules:** 21 (21 OK / 0 FAIL / 0 SKIP)
- **Atoms total:** 202 (150 proven · 52 trusted)
- **Trusted atoms (reviewed contracts):** 52
- **TODO/FIXME/XXX/HACK markers:** 4
- **Weighted health score:** 0.944 / 1.000

## Per-module breakdown

| Module | Atoms | Trusted | TODOs | Verify | Health |
|--------|------:|--------:|------:|:------:|------:|
| `std/core.mm` | 9 | 0 | 0 | OK | 1.000 |
"""


class TestParseSummary:
    def test_extracts_all_fields(self) -> None:
        entry = gsm._parse_summary(SAMPLE_METRICS_MD, "2026-04-22")
        assert entry == {
            "date": "2026-04-22",
            "modules": 21,
            "atoms": 202,
            "proven": 150,
            "trusted": 52,
            "todos": 4,
            "health": 0.944,
        }

    def test_accepts_ascii_middot(self) -> None:
        # Older snapshots may have used the ASCII middle-dot fallback.
        text = SAMPLE_METRICS_MD.replace("·", "\u00b7")
        entry = gsm._parse_summary(text, "2026-01-01")
        assert entry is not None
        assert entry["proven"] == 150
        assert entry["trusted"] == 52

    def test_returns_none_when_atoms_missing(self) -> None:
        text = "\n".join(
            line for line in SAMPLE_METRICS_MD.splitlines()
            if "Atoms total" not in line
        )
        assert gsm._parse_summary(text, "2026-04-22") is None

    def test_returns_none_when_health_missing(self) -> None:
        text = "\n".join(
            line for line in SAMPLE_METRICS_MD.splitlines()
            if "Weighted health score" not in line
        )
        assert gsm._parse_summary(text, "2026-04-22") is None

    def test_optional_fields_default_to_zero(self) -> None:
        minimal = (
            "- **Atoms total:** 10 (8 proven · 2 trusted)\n"
            "- **Weighted health score:** 0.800 / 1.000\n"
        )
        entry = gsm._parse_summary(minimal, "2026-04-22")
        assert entry is not None
        assert entry["modules"] == 0
        assert entry["todos"] == 0
        assert entry["atoms"] == 10
        assert entry["health"] == 0.800


def _sample_row(
    path: str = "std/core.mm",
    atoms: int = 5,
    trusted: int = 1,
    todos: int = 0,
    verified: str = "OK",
    health: float = 0.95,
) -> dict:
    return {
        "path": path,
        "atoms": atoms,
        "trusted": trusted,
        "todos": todos,
        "verified": verified,
        "health": health,
    }


class TestRenderMarkdownHistory:
    def test_history_section_rendered(self) -> None:
        rows = [_sample_row()]
        history = [
            {
                "date": "2026-04-22",
                "modules": 21,
                "atoms": 202,
                "proven": 150,
                "trusted": 52,
                "todos": 4,
                "health": 0.944,
            },
            {
                "date": "2026-04-19",
                "modules": 20,
                "atoms": 190,
                "proven": 138,
                "trusted": 52,
                "todos": 5,
                "health": 0.930,
            },
        ]
        md = gsm._render_markdown(rows, history)
        assert "## History" in md
        assert "| Date | Modules | Atoms | Proven | Trusted | TODOs | Health |" in md
        assert "| 2026-04-22 | 21 | 202 | 150 | 52 | 4 | 0.944 |" in md
        assert "| 2026-04-19 | 20 | 190 | 138 | 52 | 5 | 0.930 |" in md
        # History comes after the per-module breakdown.
        assert md.index("## Per-module breakdown") < md.index("## History")

    def test_empty_history_shows_placeholder(self) -> None:
        md = gsm._render_markdown([_sample_row()], [])
        assert "## History" in md
        assert "_No history available._" in md
        # And the history table header should NOT appear.
        assert "| Date | Modules |" not in md

    def test_history_defaults_to_empty(self) -> None:
        md = gsm._render_markdown([_sample_row()])
        assert "## History" in md
        assert "_No history available._" in md


class TestCollectHistory:
    def test_walks_real_commit_history(self, tmp_path: Path) -> None:
        """End-to-end smoke: a temp git repo with two metrics commits."""
        env = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.com",
               "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.com"}
        subprocess.run(["git", "init", "-q", "-b", "main", str(tmp_path)],
                       check=True, env={**env})
        docs = tmp_path / "docs"
        docs.mkdir()
        metrics = docs / "STDLIB_METRICS.md"

        metrics.write_text(
            "## Summary\n\n"
            "- **Modules:** 10 (10 OK / 0 FAIL / 0 SKIP)\n"
            "- **Atoms total:** 100 (80 proven · 20 trusted)\n"
            "- **TODO/FIXME/XXX/HACK markers:** 1\n"
            "- **Weighted health score:** 0.900 / 1.000\n",
            encoding="utf-8",
        )
        subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
        subprocess.run(
            ["git", "-C", str(tmp_path), "commit", "-q", "-m", "first",
             "--date=2026-01-01T00:00:00"],
            check=True, env={**env, "GIT_AUTHOR_DATE": "2026-01-01T00:00:00",
                             "GIT_COMMITTER_DATE": "2026-01-01T00:00:00"},
        )

        metrics.write_text(
            "## Summary\n\n"
            "- **Modules:** 12 (12 OK / 0 FAIL / 0 SKIP)\n"
            "- **Atoms total:** 120 (100 proven · 20 trusted)\n"
            "- **TODO/FIXME/XXX/HACK markers:** 2\n"
            "- **Weighted health score:** 0.920 / 1.000\n",
            encoding="utf-8",
        )
        subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
        subprocess.run(
            ["git", "-C", str(tmp_path), "commit", "-q", "-m", "second"],
            check=True, env={**env, "GIT_AUTHOR_DATE": "2026-02-03T00:00:00",
                             "GIT_COMMITTER_DATE": "2026-02-03T00:00:00"},
        )

        history = gsm._collect_history(tmp_path)
        assert len(history) == 2
        # Sorted descending by date.
        assert history[0]["date"] == "2026-02-03"
        assert history[0]["atoms"] == 120
        assert history[1]["date"] == "2026-01-01"
        assert history[1]["atoms"] == 100

    def test_same_date_deduplicates_to_latest(self, tmp_path: Path) -> None:
        env = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.com",
               "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.com"}
        subprocess.run(["git", "init", "-q", "-b", "main", str(tmp_path)],
                       check=True, env={**env})
        docs = tmp_path / "docs"
        docs.mkdir()
        metrics = docs / "STDLIB_METRICS.md"

        def _commit(atoms: int, when: str) -> None:
            metrics.write_text(
                "## Summary\n\n"
                f"- **Modules:** 1 (1 OK / 0 FAIL / 0 SKIP)\n"
                f"- **Atoms total:** {atoms} ({atoms} proven · 0 trusted)\n"
                f"- **TODO/FIXME/XXX/HACK markers:** 0\n"
                f"- **Weighted health score:** 1.000 / 1.000\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
            subprocess.run(
                ["git", "-C", str(tmp_path), "commit", "-q", "-m", when],
                check=True, env={**env, "GIT_AUTHOR_DATE": when,
                                 "GIT_COMMITTER_DATE": when},
            )

        _commit(10, "2026-03-01T08:00:00")
        _commit(20, "2026-03-01T18:00:00")  # same date, later time

        history = gsm._collect_history(tmp_path)
        assert len(history) == 1
        # Newest same-date commit wins.
        assert history[0]["date"] == "2026-03-01"
        assert history[0]["atoms"] == 20

    def test_returns_empty_outside_repo(self, tmp_path: Path) -> None:
        # Not a git repo at all → git log exits non-zero → empty result.
        assert gsm._collect_history(tmp_path) == []
