//! Auto-generated FFI contract property tests for std/file.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_file_read_file(
            _case in 0u8..=0u8,
        ) {
    let (path, temp_path_for_cleanup) = mumei_ffi_tests::temp_path_handle("path");
    std::fs::write(&temp_path_for_cleanup, "contract").unwrap();
    prop_assume!(path > 0);
    let result = mumei_core::ffi::file::file_read(path);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    let _ = std::fs::remove_file(temp_path_for_cleanup);
    }
}

proptest! {
    #[test]
        fn contract_file_write_file(
            _case in 0u8..=0u8,
        ) {
    let (path, temp_path_for_cleanup) = mumei_ffi_tests::temp_path_handle("path");
    prop_assume!(path > 0);
    let content = mumei_ffi_tests::string_handle("contract");
    prop_assume!(content > 0);
    let result = mumei_core::ffi::file::file_write(path, content);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    let _ = std::fs::remove_file(temp_path_for_cleanup);
    }
}

proptest! {
    #[test]
        fn contract_file_exists(
            _case in 0u8..=0u8,
        ) {
    let (path, temp_path_for_cleanup) = mumei_ffi_tests::temp_path_handle("path");
    std::fs::write(&temp_path_for_cleanup, "contract").unwrap();
    prop_assume!(path > 0);
    let result = mumei_core::ffi::file::file_exists(path);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    let _ = std::fs::remove_file(temp_path_for_cleanup);
    }
}

proptest! {
    #[test]
        fn contract_file_remove(
            _case in 0u8..=0u8,
        ) {
    let (path, temp_path_for_cleanup) = mumei_ffi_tests::temp_path_handle("path");
    std::fs::write(&temp_path_for_cleanup, "contract").unwrap();
    prop_assume!(path > 0);
    let result = mumei_core::ffi::file::file_delete(path);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    let _ = std::fs::remove_file(temp_path_for_cleanup);
    }
}
