//! Auto-generated FFI contract property tests for std/http_secure.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_http_secure_secure_get(
            _case in 0u8..=0u8,
        ) {
    let url_c = mumei_ffi_tests::https_error_url();
    let result = mumei_core::ffi::http::http_get(url_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_secure_post(
            body_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let url_c = mumei_ffi_tests::https_error_url();
    let body_filtered: String = body_str.chars().filter(|c| *c != '\0').collect();
    let body_c = std::ffi::CString::new(body_filtered).unwrap();
    let result = mumei_core::ffi::http::http_post(url_c.as_ptr(), body_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_secure_put(
            body_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let url_c = mumei_ffi_tests::https_error_url();
    let body_filtered: String = body_str.chars().filter(|c| *c != '\0').collect();
    let body_c = std::ffi::CString::new(body_filtered).unwrap();
    let result = mumei_core::ffi::http::http_put(url_c.as_ptr(), body_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_secure_delete(
            _case in 0u8..=0u8,
        ) {
    let url_c = mumei_ffi_tests::https_error_url();
    let result = mumei_core::ffi::http::http_delete(url_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_status(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_status(handle);
    prop_assert!(result == 0 || (result >= 100 && result <= 599), "ensures: result == 0 || (100 <= result <= 599), got {}", result);
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_body(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_body(handle);
    prop_assert!(mumei_ffi_tests::contract_result_observed(&result));
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_is_ok(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_is_ok(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_secure_free(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_free(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    }
}
#[test]
fn edge_http_secure_error_url_is_bounded() {
    let url = mumei_ffi_tests::https_error_url();
    let handle = mumei_core::ffi::http::http_get(url.as_ptr());
    assert!(handle >= 0);
    if handle > 0 {
        let status = mumei_core::ffi::http::http_status(handle);
        assert!(status == 0 || (100..=599).contains(&status));
        mumei_core::ffi::http::http_free(handle);
    }
}
