//! Auto-generated FFI contract property tests for std/http.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_http_get(
            _case in 0u8..=0u8,
        ) {
    let url_c = mumei_ffi_tests::local_http_url();
    let result = mumei_core::ffi::http::http_get(url_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_post(
            body_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let url_c = mumei_ffi_tests::local_http_url();
    let body_filtered: String = body_str.chars().filter(|c| *c != '\0').collect();
    let body_c = std::ffi::CString::new(body_filtered).unwrap();
    let result = mumei_core::ffi::http::http_post(url_c.as_ptr(), body_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_put(
            body_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let url_c = mumei_ffi_tests::local_http_url();
    let body_filtered: String = body_str.chars().filter(|c| *c != '\0').collect();
    let body_c = std::ffi::CString::new(body_filtered).unwrap();
    let result = mumei_core::ffi::http::http_put(url_c.as_ptr(), body_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_delete(
            _case in 0u8..=0u8,
        ) {
    let url_c = mumei_ffi_tests::local_http_url();
    let result = mumei_core::ffi::http::http_delete(url_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_status(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_status(handle);
    prop_assert!(result == 0 || (result >= 100 && result <= 599), "ensures: result == 0 || (100 <= result <= 599), got {}", result);
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_body(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_body(handle);
    prop_assert!(mumei_ffi_tests::contract_result_observed(&result));
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_body_json(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_body_json(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_header_get(
            name_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let name_filtered: String = name_str.chars().filter(|c| *c != '\0').collect();
    let name_c = std::ffi::CString::new(name_filtered).unwrap();
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_header_get(handle, name_c.as_ptr());
    prop_assert!(mumei_ffi_tests::contract_result_observed(&result));
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_header_set(
            name_str in "[a-zA-Z0-9 _.,]{0,128}",
            value_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let name_filtered: String = name_str.chars().filter(|c| *c != '\0').collect();
    let name_c = std::ffi::CString::new(name_filtered).unwrap();
    let value_filtered: String = value_str.chars().filter(|c| *c != '\0').collect();
    let value_c = std::ffi::CString::new(value_filtered).unwrap();
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_header_set(handle, name_c.as_ptr(), value_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_is_ok(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_is_ok(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::http::http_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_http_is_error(
            handle in 0i64..=1000i64,
        ) {
    let result = mumei_core::ffi::http::http_is_error(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_free(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::http_response_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::http::http_free(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    }
}
#[test]
fn edge_http_status_and_header_paths() {
    let handle = mumei_ffi_tests::http_response_handle();
    assert!(handle > 0);
    let status = mumei_core::ffi::http::http_status(handle);
    assert!(status == 0 || (100..=599).contains(&status));

    let header = mumei_ffi_tests::c_string("X-Mumei-Contract");
    let value = mumei_core::ffi::http::http_header_get(handle, header.as_ptr());
    assert!(mumei_ffi_tests::contract_result_observed(&value));
    mumei_core::ffi::http::http_free(handle);
}
