//! Auto-generated FFI contract property tests for std/hmac.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_hmac_hmac_sha256(
            _case in 0u8..=0u8,
        ) {
    let key = mumei_ffi_tests::string_handle("key");
    prop_assume!(key > 0);
    let message = mumei_ffi_tests::string_handle("message");
    prop_assume!(message > 0);
    let result = mumei_core::ffi::crypto::crypto_hmac_sha256(key, message);
    prop_assert!(result > 0, "ensures: result > 0, got {}", result);
    mumei_core::ffi::json::mumei_str_free(key);
    mumei_core::ffi::json::mumei_str_free(message);
    mumei_core::ffi::json::mumei_str_free(result);
    }
}
