//! Auto-generated FFI contract property tests for std/json.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_json_parse(
            input_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let input_filtered: String = input_str.chars().filter(|c| *c != '\0').collect();
    let input_c = std::ffi::CString::new(input_filtered).unwrap();
    let result = mumei_core::ffi::json::json_parse(input_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_stringify(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_stringify(handle);
    prop_assert!(mumei_ffi_tests::contract_result_observed(&result));
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_get(
            key_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let key_filtered: String = key_str.chars().filter(|c| *c != '\0').collect();
    let key_c = std::ffi::CString::new(key_filtered).unwrap();
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_get(handle, key_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_get_int(
            key_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let key_filtered: String = key_str.chars().filter(|c| *c != '\0').collect();
    let key_c = std::ffi::CString::new(key_filtered).unwrap();
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_get_int(handle, key_c.as_ptr());
    prop_assert!(mumei_ffi_tests::contract_result_observed(&result));
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_get_str(
            key_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let key_filtered: String = key_str.chars().filter(|c| *c != '\0').collect();
    let key_c = std::ffi::CString::new(key_filtered).unwrap();
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_get_str(handle, key_c.as_ptr());
    prop_assert!(mumei_ffi_tests::contract_result_observed(&result));
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_get_bool(
            key_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let key_filtered: String = key_str.chars().filter(|c| *c != '\0').collect();
    let key_c = std::ffi::CString::new(key_filtered).unwrap();
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_get_bool(handle, key_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_array_len(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::json_array_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_array_len(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_array_get(
            index in 0i64..=1000i64,
        ) {
    let handle = mumei_ffi_tests::json_array_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_array_get(handle, index);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_is_null(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_is_null(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_is_object(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_is_object(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_is_array(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_is_array(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_object_new(
            _case in 0u8..=0u8,
        ) {
    let result = mumei_core::ffi::json::json_object_new();
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_object_set(
            key_str in "[a-zA-Z0-9 _.,]{0,128}",
            value in 0i64..=1000i64,
        ) {
    let key_filtered: String = key_str.chars().filter(|c| *c != '\0').collect();
    let key_c = std::ffi::CString::new(key_filtered).unwrap();
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_object_set(handle, key_c.as_ptr(), value);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_array_new(
            _case in 0u8..=0u8,
        ) {
    let result = mumei_core::ffi::json::json_array_new();
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_array_push(
            value in 0i64..=1000i64,
        ) {
    let handle = mumei_ffi_tests::json_array_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_array_push(handle, value);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    mumei_core::ffi::json::json_free(handle);
    }
}

proptest! {
    #[test]
        fn contract_json_from_int(
            value in 0i64..=1000i64,
        ) {
    let result = mumei_core::ffi::json::json_from_int(value);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_from_str(
            value_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let value_filtered: String = value_str.chars().filter(|c| *c != '\0').collect();
    let value_c = std::ffi::CString::new(value_filtered).unwrap();
    let result = mumei_core::ffi::json::json_from_str(value_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_from_bool(
            value in 0i64..=1i64,
        ) {
    let result = mumei_core::ffi::json::json_from_bool(value);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_free(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::json_object_handle();
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::json_free(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_json_str_free(
            _case in 0u8..=0u8,
        ) {
    let handle = mumei_ffi_tests::string_handle("contract");
    prop_assume!(handle > 0);
    let result = mumei_core::ffi::json::string_free(handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    }
}
