//! Auto-generated FFI contract property tests for std/signature.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_signature_verify_signature(
            _case in 0u8..=0u8,
        ) {
    let public_key = mumei_ffi_tests::string_handle("public-key");
    prop_assume!(public_key > 0);
    let message = mumei_ffi_tests::string_handle("message");
    prop_assume!(message > 0);
    let signature = mumei_ffi_tests::string_handle("3d461619e939ce5274da929c96d321ba4a7615206637cc31db6b74fa64e97fc9");
    prop_assume!(signature > 0);
    let result = mumei_core::ffi::crypto::crypto_verify_signature(public_key, message, signature);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::json::mumei_str_free(public_key);
    mumei_core::ffi::json::mumei_str_free(message);
    mumei_core::ffi::json::mumei_str_free(signature);
    }
}
