//! Auto-generated FFI contract property tests for std/http_server.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_http_server_bind_server(
            _case in 0u8..=0u8,
        ) {
    let addr_c = mumei_ffi_tests::unique_local_addr();
    let result = mumei_core::ffi::http_server::http_server_bind(addr_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    }
}

proptest! {
    #[test]
        fn contract_http_server_listen_server(
            _case in 0u8..=0u8,
        ) {
    let server_handle = mumei_ffi_tests::server_handle();
    prop_assume!(server_handle > 0);
    let result = mumei_core::ffi::http_server::http_server_listen(server_handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::http_server::http_server_free(server_handle);
    }
}

proptest! {
    #[test]
        fn contract_http_server_accept_request(
            _case in 0u8..=0u8,
        ) {
    let (server_handle, client_for_accept_cleanup) = mumei_ffi_tests::server_handle_with_pending_client();
    prop_assume!(server_handle > 0);
    let result = mumei_core::ffi::http_server::http_server_accept(server_handle);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    if result > 0 { mumei_core::ffi::http_server::http_request_free(result); }
    let _ = client_for_accept_cleanup.join();
    mumei_core::ffi::http_server::http_server_free(server_handle);
    }
}

proptest! {
    #[test]
        fn contract_http_server_send_response(
            status in 100i64..=599i64,
            body_str in "[a-zA-Z0-9 _.,]{0,128}",
        ) {
    let body_filtered: String = body_str.chars().filter(|c| *c != '\0').collect();
    let body_c = std::ffi::CString::new(body_filtered).unwrap();
    let (server_handle_for_cleanup, req_handle, client_for_request_cleanup) = mumei_ffi_tests::server_request_handle();
    prop_assume!(server_handle_for_cleanup > 0);
    prop_assume!(req_handle > 0);
    let result = mumei_core::ffi::http_server::http_server_respond(req_handle, status, body_c.as_ptr());
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::http_server::http_request_free(req_handle);
    let _ = client_for_request_cleanup.join();
    mumei_core::ffi::http_server::http_server_free(server_handle_for_cleanup);
    }
}
