//! Auto-generated FFI contract property tests for std/hash.mm
//!
//! Generated by scripts/ffi_contract_test_gen.py
//! DO NOT EDIT — regenerate with:
//!   python scripts/ffi_contract_test_gen.py
//!
//! Tests verify that the Rust FFI backend satisfies the
//! requires/ensures contracts declared in the .mm source.

use proptest::prelude::*;

proptest! {
    #[test]
        fn contract_hash_sha256(
            _case in 0u8..=0u8,
        ) {
    let input = mumei_ffi_tests::string_handle("abc");
    prop_assume!(input > 0);
    let result = mumei_core::ffi::crypto::crypto_sha256(input);
    prop_assert!(result > 0, "ensures: result > 0, got {}", result);
    mumei_core::ffi::json::mumei_str_free(input);
    mumei_core::ffi::json::mumei_str_free(result);
    }
}

proptest! {
    #[test]
        fn contract_hash_hash_eq(
            _case in 0u8..=0u8,
        ) {
    let left = mumei_ffi_tests::string_handle("digest");
    prop_assume!(left > 0);
    let right = mumei_ffi_tests::string_handle("digest");
    prop_assume!(right > 0);
    let result = mumei_core::ffi::crypto::crypto_hash_eq(left, right);
    prop_assert!(result >= 0, "ensures: result >= 0, got {}", result);
    prop_assert!(result <= 1, "ensures: result <= 1, got {}", result);
    mumei_core::ffi::json::mumei_str_free(left);
    mumei_core::ffi::json::mumei_str_free(right);
    }
}
