//! FFI glue code generator for Rust.
//!
//! **NOT a transpiler** — this emitter does NOT convert mumei code into Rust.
//! It generates `extern "C"` bindings and safe Rust wrapper functions that call
//! compiled mumei binaries (`.so`/`.dll`) via FFI. This is the same layer as
//! `CHeaderEmitter` (which generates `.h` files).
//!
//! The generated `.rs` file contains:
//! - An `extern "C"` block with the raw function declaration
//! - A safe Rust wrapper function with runtime contract checks
//!   (`assert!` for requires, `debug_assert!` for ensures)
//! - Doc comments with `/// # Precondition` / `/// # Postcondition`

use mumei_core::emitter::{Artifact, ArtifactKind, Emitter};
use mumei_core::hir::HirAtom;
use mumei_core::parser::ExternBlock;
use mumei_core::verification::{ModuleEnv, MumeiResult};
use std::path::Path;

/// Map a mumei type name to its Rust FFI equivalent.
fn mumei_type_to_rust(type_name: &str) -> &str {
    match type_name {
        "i64" => "i64",
        "i32" => "i32",
        "u64" => "u64",
        "u32" => "u32",
        "f64" => "f64",
        "f32" => "f32",
        "bool" => "i64", // mumei compiles bool to i64 in LLVM IR
        "Str" | "String" => "*const std::os::raw::c_char",
        _ => "i64", // default fallback for refined types based on i64
    }
}

/// FFI glue code generator for Rust.
///
/// Generates `extern "C"` bindings and safe Rust wrapper functions
/// that call compiled mumei binaries via FFI. NOT a transpiler.
pub struct RustWrapperEmitter;

impl Emitter for RustWrapperEmitter {
    fn emit(
        &self,
        hir_atom: &HirAtom,
        output_path: &Path,
        module_env: &ModuleEnv,
        _extern_blocks: &[ExternBlock],
    ) -> MumeiResult<Vec<Artifact>> {
        let atom = &hir_atom.atom;
        // Sanitize qualified names (e.g., "MyStruct::my_method" → "MyStruct__my_method")
        // to produce valid Rust identifiers, matching CHeaderEmitter behavior.
        let fn_name = atom.name.replace("::", "__");
        let mut rs = String::new();

        // File header
        rs.push_str("// Auto-generated by mumei RustWrapperEmitter\n");
        rs.push_str("// FFI glue code — NOT transpiled mumei source.\n");
        rs.push_str("// This file provides safe Rust wrappers around a compiled mumei binary.\n\n");

        // Build parameter lists
        let params: Vec<(String, String)> = atom
            .params
            .iter()
            .map(|p| {
                let type_name = p.type_name.as_deref().unwrap_or("i64");
                let resolved = module_env.resolve_base_type(type_name);
                let rust_type = mumei_type_to_rust(&resolved).to_string();
                (p.name.clone(), rust_type)
            })
            .collect();

        let return_type = {
            let ret = atom.return_type.as_deref().unwrap_or("i64");
            let resolved = module_env.resolve_base_type(ret);
            mumei_type_to_rust(&resolved).to_string()
        };

        // extern "C" block
        rs.push_str("extern \"C\" {\n");
        let extern_params: Vec<String> = params
            .iter()
            .map(|(name, ty)| format!("    {}: {}", name, ty))
            .collect();
        rs.push_str(&format!(
            "    fn {}(\n{}\n    ) -> {};\n",
            fn_name,
            extern_params.join(",\n"),
            return_type
        ));
        rs.push_str("}\n\n");

        // Doc comments for the safe wrapper
        rs.push_str(&format!(
            "/// Safe wrapper for the verified `{}` atom.\n",
            atom.name
        ));
        rs.push_str("///\n");
        rs.push_str("/// # Safety\n");
        rs.push_str("/// Calls into a compiled mumei binary via FFI.\n");
        rs.push_str("/// Preconditions are checked at runtime via `assert!`.\n");
        rs.push_str("/// Postconditions are checked via `debug_assert!`.\n");
        if atom.requires != "true" {
            rs.push_str("///\n");
            rs.push_str(&format!("/// # Precondition\n/// `{}`\n", atom.requires));
        }
        if atom.ensures != "true" {
            rs.push_str("///\n");
            rs.push_str(&format!("/// # Postcondition\n/// `{}`\n", atom.ensures));
        }

        // Safe wrapper function
        let fn_params: Vec<String> = params
            .iter()
            .map(|(name, ty)| format!("{}: {}", name, ty))
            .collect();
        rs.push_str(&format!(
            "pub fn {}_safe({}) -> {} {{\n",
            fn_name,
            fn_params.join(", "),
            return_type
        ));

        // Runtime precondition check
        if atom.requires != "true" {
            rs.push_str(&format!(
                "    assert!({}, \"precondition violated: {}\");\n",
                translate_contract_to_rust(&atom.requires, &params),
                atom.requires.replace('"', "\\\"")
            ));
        }

        // Unsafe FFI call
        rs.push_str(&format!(
            "    let result = unsafe {{ {}({}) }};\n",
            fn_name,
            params
                .iter()
                .map(|(name, _)| name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));

        // Runtime postcondition check (debug only)
        if atom.ensures != "true" {
            rs.push_str(&format!(
                "    debug_assert!({}, \"postcondition violated: {}\");\n",
                translate_contract_to_rust(&atom.ensures, &params),
                atom.ensures.replace('"', "\\\"")
            ));
        }

        rs.push_str("    result\n");
        rs.push_str("}\n");

        let rs_path = output_path.with_extension("rs");

        Ok(vec![Artifact {
            name: rs_path,
            data: rs.into_bytes(),
            kind: ArtifactKind::Source,
        }])
    }
}

/// Translate a mumei contract expression to valid Rust syntax.
///
/// Handles common patterns:
/// - `&&` / `||` → kept as-is (valid Rust)
/// - `result` → kept as-is (local variable in wrapper)
/// - Parameter names → kept as-is
fn translate_contract_to_rust(contract: &str, _params: &[(String, String)]) -> String {
    // mumei contract syntax is close to Rust — &&, ||, ==, !=, >=, <= all work.
    // The main translation needed is `=>` (implication) to `!a || b`.
    let result = contract.to_string();
    // For now, simple contracts pass through directly.
    // Complex contracts with `=>` would need transformation.
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use mumei_core::hir::{HirEffectSet, HirExpr, HirStmt};
    use mumei_core::parser::ast::{Atom, Expr, Param, Span, Stmt, TrustLevel};
    use mumei_core::verification::ModuleEnv;

    fn make_param(name: &str, type_name: &str) -> Param {
        Param {
            name: name.to_string(),
            type_name: Some(type_name.to_string()),
            type_ref: None,
            is_ref: false,
            is_ref_mut: false,
            fn_contract_requires: None,
            fn_contract_ensures: None,
        }
    }

    fn make_hir_atom(
        name: &str,
        params: Vec<Param>,
        requires: &str,
        ensures: &str,
        return_type: Option<&str>,
    ) -> HirAtom {
        HirAtom {
            body: HirStmt::Expr(HirExpr::Number(0)),
            requires_hir: HirExpr::Number(1),
            ensures_hir: HirExpr::Number(1),
            atom: Atom {
                name: name.to_string(),
                type_params: vec![],
                where_bounds: vec![],
                params,
                requires: requires.to_string(),
                forall_constraints: vec![],
                ensures: ensures.to_string(),
                body_expr: "0".to_string(),
                consumed_params: vec![],
                resources: vec![],
                is_async: false,
                trust_level: TrustLevel::Verified,
                max_unroll: None,
                invariant: None,
                effects: vec![],
                return_type: return_type.map(|s| s.to_string()),
                span: Span::default(),
                effect_pre: std::collections::HashMap::new(),
                effect_post: std::collections::HashMap::new(),
            },
            body_stmt: Stmt::Expr(Expr::Number(0), Span::default()),
            effect_set: HirEffectSet::default(),
        }
    }

    #[test]
    fn test_rust_wrapper_basic() {
        let hir = make_hir_atom(
            "safe_add",
            vec![make_param("a", "i64"), make_param("b", "i64")],
            "a >= 0 && b >= 0",
            "result == a + b",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = RustWrapperEmitter
            .emit(&hir, Path::new("/tmp/safe_add"), &module_env, &[])
            .unwrap();

        assert_eq!(artifacts.len(), 1);
        assert_eq!(
            artifacts[0].name,
            std::path::PathBuf::from("/tmp/safe_add.rs")
        );
        assert_eq!(artifacts[0].kind, ArtifactKind::Source);

        let rs = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(rs.contains("extern \"C\""));
        assert!(rs.contains("fn safe_add("));
        assert!(rs.contains("pub fn safe_add_safe("));
        assert!(rs.contains("assert!("));
        assert!(rs.contains("debug_assert!("));
        assert!(rs.contains("/// # Precondition"));
        assert!(rs.contains("/// # Postcondition"));
        assert!(rs.contains("NOT transpiled mumei source"));
    }

    #[test]
    fn test_rust_wrapper_no_contracts() {
        let hir = make_hir_atom(
            "identity",
            vec![make_param("x", "i64")],
            "true",
            "true",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = RustWrapperEmitter
            .emit(&hir, Path::new("/tmp/identity"), &module_env, &[])
            .unwrap();

        let rs = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(!rs.contains("assert!("));
        assert!(!rs.contains("debug_assert!("));
        assert!(!rs.contains("/// # Precondition"));
        assert!(!rs.contains("/// # Postcondition"));
    }

    #[test]
    fn test_type_mapping() {
        assert_eq!(mumei_type_to_rust("i64"), "i64");
        assert_eq!(mumei_type_to_rust("i32"), "i32");
        assert_eq!(mumei_type_to_rust("u64"), "u64");
        assert_eq!(mumei_type_to_rust("bool"), "i64");
        assert_eq!(mumei_type_to_rust("Str"), "*const std::os::raw::c_char");
        assert_eq!(mumei_type_to_rust("UnknownType"), "i64");
    }
}
