//! FFI glue code generator for Rust.
//!
//! **NOT a transpiler** — this emitter does NOT convert mumei code into Rust.
//! It generates `extern "C"` bindings and safe Rust wrapper functions that call
//! compiled mumei binaries (`.so`/`.dll`) via FFI. This is the same layer as
//! `CHeaderEmitter` (which generates `.h` files).
//!
//! The generated `.rs` file contains:
//! - An `extern "C"` block with the raw function declaration
//! - A safe Rust wrapper function with runtime contract checks
//!   (`assert!` for requires, `debug_assert!` for ensures)
//! - Doc comments with `/// # Precondition` / `/// # Postcondition`

use mumei_core::contract_host::{
    contract_text_to_host, quantifier_source_text, quantifier_to_host, ContractVars, HostTarget,
};
use mumei_core::emitter::{Artifact, ArtifactKind, Emitter};
use mumei_core::hir::HirAtom;
use mumei_core::lowering::{lower, LoweredType};
use mumei_core::parser::ExternBlock;
use mumei_core::verification::{ModuleEnv, MumeiResult};
use std::path::Path;

fn format_lowered_type_to_rust(lowered: &LoweredType) -> &'static str {
    match lowered {
        LoweredType::I64 => "i64",
        LoweredType::I32 => "i32",
        LoweredType::U64 => "u64",
        LoweredType::U32 => "u32",
        LoweredType::F64 => "f64",
        LoweredType::F32 => "f32",
        LoweredType::Bool => "i64",
        LoweredType::Str => "*const std::os::raw::c_char",
        LoweredType::Array(inner) if matches!(**inner, LoweredType::I64) => "*const i64",
        LoweredType::Array(_) | LoweredType::Other(_) => "i64",
    }
}

/// Map a mumei type name to its Rust FFI equivalent.
fn mumei_type_to_rust(type_name: &str) -> &str {
    format_lowered_type_to_rust(&lower(type_name))
}

/// FFI glue code generator for Rust.
///
/// Generates `extern "C"` bindings and safe Rust wrapper functions
/// that call compiled mumei binaries via FFI. NOT a transpiler.
pub struct RustWrapperEmitter;

impl Emitter for RustWrapperEmitter {
    fn emit(
        &self,
        hir_atom: &HirAtom,
        output_path: &Path,
        module_env: &ModuleEnv,
        _extern_blocks: &[ExternBlock],
    ) -> MumeiResult<Vec<Artifact>> {
        let signature = &hir_atom.signature;
        let contract = &hir_atom.contract;
        // Sanitize qualified names (e.g., "MyStruct::my_method" → "MyStruct_my_method")
        // to produce valid Rust identifiers, matching CHeaderEmitter behavior.
        let fn_name = signature.name.replace("::", "_");
        let mut rs = String::new();

        // File header
        rs.push_str("// Auto-generated by mumei RustWrapperEmitter\n");
        rs.push_str("// FFI glue code — NOT transpiled mumei source.\n");
        rs.push_str("// This file provides safe Rust wrappers around a compiled mumei binary.\n\n");

        // Build parameter lists
        let params: Vec<(String, String)> = signature
            .params
            .iter()
            .map(|p| {
                let type_name = p.ty.as_deref().unwrap_or("i64");
                let resolved = module_env.resolve_base_type(type_name);
                let rust_type = mumei_type_to_rust(&resolved).to_string();
                // `consume`/`ref` are mumei ownership markers — emit the bare
                // name in host code.
                (p.name.clone(), rust_type)
            })
            .collect();

        let return_type = {
            let ret = signature.return_type.as_deref().unwrap_or("i64");
            let resolved = module_env.resolve_base_type(ret);
            mumei_type_to_rust(&resolved).to_string()
        };

        // extern "C" block
        rs.push_str("extern \"C\" {\n");
        let extern_params: Vec<String> = params
            .iter()
            .map(|(name, ty)| format!("    {}: {}", name, ty))
            .collect();
        rs.push_str(&format!(
            "    fn {}(\n{}\n    ) -> {};\n",
            fn_name,
            extern_params.join(",\n"),
            return_type
        ));
        rs.push_str("}\n\n");

        // Doc comments for the safe wrapper
        rs.push_str(&format!(
            "/// Safe wrapper for the verified `{}` atom.\n",
            signature.name
        ));
        rs.push_str("///\n");
        rs.push_str("/// # Safety\n");
        rs.push_str("/// Calls into a compiled mumei binary via FFI.\n");
        rs.push_str("/// Preconditions are checked at runtime via `assert!`.\n");
        rs.push_str("/// Postconditions are checked via `debug_assert!`.\n");
        if contract.requires_text != "true" {
            rs.push_str("///\n");
            rs.push_str(&format!(
                "/// # Precondition\n/// `{}`\n",
                contract.requires_text
            ));
        }
        if contract.ensures_text != "true" {
            rs.push_str("///\n");
            rs.push_str(&format!(
                "/// # Postcondition\n/// `{}`\n",
                contract.ensures_text
            ));
        }

        // Safe wrapper function
        let fn_params: Vec<String> = params
            .iter()
            .map(|(name, ty)| format!("{}: {}", name, ty))
            .collect();
        rs.push_str(&format!(
            "pub fn {}_safe({}) -> {} {{\n",
            fn_name,
            fn_params.join(", "),
            return_type
        ));

        // Variable kinds for contract translation (pointer indexing, etc.).
        let vars = ContractVars::from_signature(signature, Some(module_env));

        // Runtime precondition check
        if contract.requires_text != "true" {
            match translate_contract_to_rust(&contract.requires_text, &vars) {
                Some(cond) => rs.push_str(&format!(
                    "    assert!({}, \"precondition violated: {}\");\n",
                    cond,
                    escape_message(&contract.requires_text)
                )),
                None => rs.push_str(&format!(
                    "    // mumei: requires not expressible as a Rust runtime check; left to verification: {}\n",
                    contract.requires_text
                )),
            }
        }
        // Hoisted `forall`/`exists` requires conjuncts: assert each as its own
        // line (`(start..end).all(|v| cond)` / `.any(...)`).
        for quantifier in &contract.quantifiers {
            let source = quantifier_source_text(quantifier);
            match quantifier_to_host(quantifier, &vars, HostTarget::Rust) {
                Some(cond) => rs.push_str(&format!(
                    "    assert!({}, \"precondition violated: {}\");\n",
                    cond,
                    escape_message(&source)
                )),
                None => rs.push_str(&format!(
                    "    // mumei: quantified requires not expressible as a Rust runtime check; left to verification: {}\n",
                    source
                )),
            }
        }

        // Unsafe FFI call
        rs.push_str(&format!(
            "    let result = unsafe {{ {}({}) }};\n",
            fn_name,
            params
                .iter()
                .map(|(name, _)| name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));

        // Runtime postcondition check (debug only)
        if contract.ensures_text != "true" {
            match translate_contract_to_rust(&contract.ensures_text, &vars) {
                Some(cond) => rs.push_str(&format!(
                    "    debug_assert!({}, \"postcondition violated: {}\");\n",
                    cond,
                    escape_message(&contract.ensures_text)
                )),
                None => rs.push_str(&format!(
                    "    // mumei: ensures not expressible as a Rust runtime check; left to verification: {}\n",
                    contract.ensures_text
                )),
            }
        }

        rs.push_str("    result\n");
        rs.push_str("}\n");

        let rs_path = output_path.with_extension("rs");

        Ok(vec![Artifact {
            name: rs_path,
            data: rs.into_bytes(),
            kind: ArtifactKind::Source,
        }])
    }
}

/// Escape a contract source string for use inside a `"..."` assert message.
/// Backslashes must be escaped before quotes — quoting first would turn an
/// already-escaped `\"` into `\\\"` and break the string literal.
fn escape_message(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Translate a mumei contract expression to a Rust expression.
///
/// This is now AST-based (`mumei_core::contract_host`): `=>` prints as
/// `!a || b`, comparison chains (`a < b < c`) print as `a < b && b < c`,
/// `forall`/`exists` calls print as `range.all(..)`/`range.any(..)`, array
/// indexing on pointer params as `unsafe { *p.add(i) }`, and literals are
/// normalized. Returns `None` for clauses with no runtime-checkable Rust form
/// — the caller emits a degrade comment instead of invalid code.
fn translate_contract_to_rust(contract: &str, vars: &ContractVars) -> Option<String> {
    contract_text_to_host(contract, vars, HostTarget::Rust)
}

#[cfg(test)]
mod tests {
    use super::*;
    use mumei_core::hir::{lower_atom_metadata, HirEffectSet, HirExpr, HirStmt};
    use mumei_core::parser::ast::{
        Atom, Expr, Param, Quantifier, QuantifierType, Span, Stmt, TrustLevel,
    };
    use mumei_core::verification::ModuleEnv;

    fn make_param(name: &str, type_name: &str) -> Param {
        Param {
            name: name.to_string(),
            type_name: Some(type_name.to_string()),
            type_ref: None,
            is_ref: false,
            is_ref_mut: false,
            fn_contract_requires: None,
            fn_contract_ensures: None,
        }
    }

    fn make_hir_atom(
        name: &str,
        params: Vec<Param>,
        requires: &str,
        ensures: &str,
        return_type: Option<&str>,
    ) -> HirAtom {
        let body = HirStmt::Expr(HirExpr::Number(0));
        let atom = Atom {
            name: name.to_string(),
            type_params: vec![],
            where_bounds: vec![],
            params,
            trace_id: None,
            spec_metadata: std::collections::HashMap::new(),
            clause_labels: Vec::new(),
            clause_modes: Vec::new(),
            covers: Vec::new(),
            requires: requires.to_string(),
            forall_constraints: vec![],
            ensures: ensures.to_string(),
            body_expr: "0".to_string(),
            consumed_params: vec![],
            resources: vec![],
            is_async: false,
            trust_level: TrustLevel::Verified,
            max_unroll: None,
            invariant: None,
            effects: vec![],
            return_type: return_type.map(|s| s.to_string()),
            decreases: None,
            span: Span::default(),
            effect_pre: std::collections::HashMap::new(),
            effect_post: std::collections::HashMap::new(),
        };
        let (signature, contract, meta) = lower_atom_metadata(&atom, &body, None);
        HirAtom {
            body,
            signature,
            contract,
            meta,
            atom,
            body_stmt: Stmt::Expr(Expr::Number(0), Span::default()),
            effect_set: HirEffectSet::default(),
        }
    }

    fn make_hir_atom_with_quantifiers(
        name: &str,
        params: Vec<Param>,
        requires: &str,
        quantifiers: Vec<Quantifier>,
        ensures: &str,
        return_type: Option<&str>,
    ) -> HirAtom {
        let mut hir = make_hir_atom(name, params, requires, ensures, return_type);
        hir.atom.forall_constraints = quantifiers.clone();
        hir.contract.quantifiers = quantifiers
            .iter()
            .map(|q| {
                let condition_expr = mumei_core::parser::parse_expression_checked(&q.condition)
                    .ok()
                    .map(|e| mumei_core::hir::lower_expr_with_env(&e, None));
                mumei_core::hir::HirQuantifier {
                    kind: if q.q_type == QuantifierType::Exists {
                        mumei_core::hir::HirQuantifierKind::Exists
                    } else {
                        mumei_core::hir::HirQuantifierKind::ForAll
                    },
                    var: q.var.clone(),
                    start: q.start.clone(),
                    end: q.end.clone(),
                    condition: q.condition.clone(),
                    condition_expr,
                }
            })
            .collect();
        hir
    }

    #[test]
    fn test_rust_wrapper_quantified_requires_become_runtime_checks() {
        // Hoisted forall/exists become their own `assert!` lines, using the
        // end-exclusive `[start, end)` range that matches mumei semantics.
        let hir = make_hir_atom_with_quantifiers(
            "bounded",
            vec![make_param("x", "i64"), make_param("n", "i64")],
            "x >= 0 && true",
            vec![
                Quantifier {
                    q_type: QuantifierType::ForAll,
                    var: "i".to_string(),
                    start: "0".to_string(),
                    end: "n".to_string(),
                    condition: "i >= 0 && i < x".to_string(),
                },
                Quantifier {
                    q_type: QuantifierType::Exists,
                    var: "j".to_string(),
                    start: "0".to_string(),
                    end: "n".to_string(),
                    condition: "j == 0".to_string(),
                },
            ],
            "result >= 0",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = RustWrapperEmitter
            .emit(&hir, Path::new("/tmp/bounded"), &module_env, &[])
            .unwrap();
        let rs = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(
            rs.contains(
                "assert!(((0)..(n)).all(|i| i >= 0 && i < x), \"precondition violated: forall(i, 0, n, i >= 0 && i < x)\");"
            ),
            "forall should be an .all(...) runtime check:\n{rs}"
        );
        assert!(
            rs.contains(
                "assert!(((0)..(n)).any(|j| j == 0), \"precondition violated: exists(j, 0, n, j == 0)\");"
            ),
            "exists should be an .any(...) runtime check:\n{rs}"
        );
    }

    #[test]
    fn test_rust_wrapper_basic() {
        let hir = make_hir_atom(
            "safe_add",
            vec![make_param("a", "i64"), make_param("b", "i64")],
            "a >= 0 && b >= 0",
            "result == a + b",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = RustWrapperEmitter
            .emit(&hir, Path::new("/tmp/safe_add"), &module_env, &[])
            .unwrap();

        assert_eq!(artifacts.len(), 1);
        assert_eq!(
            artifacts[0].name,
            std::path::PathBuf::from("/tmp/safe_add.rs")
        );
        assert_eq!(artifacts[0].kind, ArtifactKind::Source);

        let rs = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(rs.contains("extern \"C\""));
        assert!(rs.contains("fn safe_add("));
        assert!(rs.contains("pub fn safe_add_safe("));
        assert!(rs.contains("assert!("));
        assert!(rs.contains("debug_assert!("));
        assert!(rs.contains("/// # Precondition"));
        assert!(rs.contains("/// # Postcondition"));
        assert!(rs.contains("NOT transpiled mumei source"));
    }

    #[test]
    fn test_rust_wrapper_no_contracts() {
        let hir = make_hir_atom(
            "identity",
            vec![make_param("x", "i64")],
            "true",
            "true",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = RustWrapperEmitter
            .emit(&hir, Path::new("/tmp/identity"), &module_env, &[])
            .unwrap();

        let rs = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(!rs.contains("assert!("));
        assert!(!rs.contains("debug_assert!("));
        assert!(!rs.contains("/// # Precondition"));
        assert!(!rs.contains("/// # Postcondition"));
    }

    #[test]
    fn test_contract_translation() {
        let vars = ContractVars::new();
        let tr = |s: &str| translate_contract_to_rust(s, &vars);
        assert_eq!(tr("a >= 0 && b >= 0").as_deref(), Some("a >= 0 && b >= 0"));
        assert_eq!(tr("x > 0 || y > 0").as_deref(), Some("x > 0 || y > 0"));
        // `=>` implication → `!a || b`, operands parenthesized
        assert_eq!(
            tr("x > 0 => result > 0").as_deref(),
            Some("!(x > 0) || (result > 0)")
        );
        // `=>` inside a larger expression (`=>` binds looser than `||`)
        assert_eq!(
            tr("x > 0 || y > 0 => z > 0").as_deref(),
            Some("!(x > 0 || y > 0) || (z > 0)")
        );
        // Chained `=>` is left-associative: (a => b) => c
        assert_eq!(
            tr("a > 0 => b > 0 => c > 0").as_deref(),
            Some("!(!(a > 0) || (b > 0)) || (c > 0)")
        );
        // Comparison chains normalize to `&&`-joined comparisons
        assert_eq!(tr("0 <= i < n").as_deref(), Some("0 <= i && i < n"));
        // `/` between ints → `div_euclid`, matching Z3 `Int` semantics
        // (remainder ≥ 0), not plain `/` which truncates. `as i64` pins the
        // receiver so untyped literals can call the method.
        assert_eq!(
            tr("a / b >= 0").as_deref(),
            Some("((a) as i64).div_euclid(b) >= 0")
        );
        // Quantifiers nested inside an expression still translate
        assert_eq!(
            tr("n <= 0 || forall(i, 0, n, i >= 0)").as_deref(),
            Some("n <= 0 || ((0)..(n)).all(|i| i >= 0)")
        );
        // Unparseable tail degrades to None instead of emitting broken Rust
        assert_eq!(tr("result >= 0 -> result < 10"), None);
    }

    #[test]
    fn test_contract_translation_negative_division() {
        // `div_euclid` matches Z3 `Int` division (remainder ≥ 0) exactly:
        // `(0 - 7).div_euclid(2) == -4` — Z3 `div(-7, 2) == -4`, where plain
        // `/` would give -3 and mischeck a verified clause. Negative divisors
        // diverge too: `7.div_euclid(-2) == -3` — Z3 `div(7, -2) == -3`.
        let vars = ContractVars::new();
        assert_eq!(
            translate_contract_to_rust("(0 - 7) / 2 == 0 - 4", &vars).as_deref(),
            Some("((0 - 7) as i64).div_euclid(2) == 0 - 4")
        );
        assert_eq!(
            translate_contract_to_rust("7 / (0 - 2) == 0 - 3", &vars).as_deref(),
            Some("((7) as i64).div_euclid(0 - 2) == 0 - 3")
        );
        // `u64` operands divide as u64 — `as i64` would flip the sign of a
        // dividend above `i64::MAX`; nonnegative literals adopt u64 too.
        let mut uvars = ContractVars::new();
        uvars.insert("ua", mumei_core::contract_host::ContractVarKind::UInt);
        uvars.insert("ub", mumei_core::contract_host::ContractVarKind::UInt);
        assert_eq!(
            translate_contract_to_rust("ua / ub >= 0", &uvars).as_deref(),
            Some("((ua) as u64).div_euclid(ub) >= 0")
        );
        assert_eq!(
            translate_contract_to_rust("ua / 2 >= 0", &uvars).as_deref(),
            Some("((ua) as u64).div_euclid(2) >= 0")
        );
        // Mixed signedness cannot be represented faithfully — degrade.
        assert_eq!(translate_contract_to_rust("a / ub >= 0", &uvars), None);
        // `::`-qualified names mangle to FFI symbols, never host paths —
        // `std::process::exit(0)` can never become a real host call.
        assert_eq!(
            translate_contract_to_rust("std::process::exit(0) == 0", &vars).as_deref(),
            Some("std_process_exit(0) == 0")
        );
        // Pointer indexing / field reads degrade rather than dereference an
        // unvalidated FFI pointer inside a safe wrapper.
        assert_eq!(translate_contract_to_rust("arr[i] >= 0", &vars), None);
        assert_eq!(translate_contract_to_rust("v.x >= 0", &vars), None);
        assert_eq!(
            translate_contract_to_rust("forall(i, 0, n, arr[i] >= 0)", &vars),
            None
        );
        // ...but a translatable conjunct alongside them is still enforced:
        // only the untranslatable conjunct drops.
        assert_eq!(
            translate_contract_to_rust("n > 0 && arr[i] > 0 && result >= 0", &vars).as_deref(),
            Some("n > 0 && result >= 0")
        );
    }

    #[test]
    fn test_mumei_type_to_rust_array_edge_cases() {
        assert_eq!(mumei_type_to_rust("[f64]"), "i64");
        assert_eq!(mumei_type_to_rust("[[i64]]"), "i64");
    }

    #[test]
    fn test_type_mapping() {
        assert_eq!(mumei_type_to_rust("i64"), "i64");
        assert_eq!(mumei_type_to_rust("i32"), "i32");
        assert_eq!(mumei_type_to_rust("u64"), "u64");
        assert_eq!(mumei_type_to_rust("bool"), "i64");
        assert_eq!(mumei_type_to_rust("Str"), "*const std::os::raw::c_char");
        assert_eq!(mumei_type_to_rust("[i64]"), "*const i64");
        assert_eq!(mumei_type_to_rust("UnknownType"), "i64");
    }
}
