//! FFI glue code generator for Python.
//!
//! **NOT a transpiler** — this emitter does NOT convert mumei code into Python.
//! It generates `ctypes`-based Python wrapper functions that call compiled mumei
//! binaries (`.so`/`.dll`) via FFI. This is the same layer as `CHeaderEmitter`
//! (which generates `.h` files).
//!
//! The generated `.py` file contains:
//! - Module docstring with contracts
//! - `ctypes` imports and library loading boilerplate
//! - Type-annotated Python functions with `assert` for requires

use mumei_core::contract_host::{
    contract_text_to_host, quantifier_source_text, quantifier_to_host, ContractVars, HostTarget,
};
use mumei_core::emitter::{Artifact, ArtifactKind, EmitAtom, Emitter};
use mumei_core::lowering::{lower, LoweredType};
use mumei_core::parser::ExternBlock;
use mumei_core::verification::{ModuleEnv, MumeiResult};
use std::path::Path;

fn format_lowered_type_to_ctypes(lowered: &LoweredType) -> &'static str {
    match lowered {
        LoweredType::I64 => "c_int64",
        LoweredType::I32 => "c_int32",
        LoweredType::U64 => "c_uint64",
        LoweredType::U32 => "c_uint32",
        LoweredType::F64 => "c_double",
        LoweredType::F32 => "c_float",
        LoweredType::Bool => "c_int64",
        LoweredType::Str => "c_char_p",
        LoweredType::Array(inner) if matches!(**inner, LoweredType::I64) => "POINTER(c_int64)",
        LoweredType::Array(_) | LoweredType::Other(_) => "c_int64",
    }
}

/// Map a mumei type name to its Python ctypes equivalent.
fn mumei_type_to_ctypes(type_name: &str) -> &str {
    format_lowered_type_to_ctypes(&lower(type_name))
}

fn format_lowered_type_to_python_annotation(lowered: &LoweredType) -> &'static str {
    match lowered {
        LoweredType::I64 | LoweredType::I32 | LoweredType::U64 | LoweredType::U32 => "int",
        LoweredType::F64 | LoweredType::F32 => "float",
        LoweredType::Bool => "bool",
        LoweredType::Str => "bytes",
        LoweredType::Array(inner) if matches!(**inner, LoweredType::I64) => "ctypes.Array",
        LoweredType::Array(_) | LoweredType::Other(_) => "int",
    }
}

/// Map a mumei type name to its Python type annotation.
fn mumei_type_to_python_annotation(type_name: &str) -> &str {
    format_lowered_type_to_python_annotation(&lower(type_name))
}

/// FFI glue code generator for Python.
///
/// Generates `ctypes`-based Python wrapper functions that call compiled
/// mumei binaries via FFI. NOT a transpiler.
pub struct PythonWrapperEmitter;

impl Emitter for PythonWrapperEmitter {
    fn emit(
        &self,
        emit_atom: &EmitAtom<'_>,
        output_path: &Path,
        module_env: &ModuleEnv,
        _extern_blocks: &[ExternBlock],
    ) -> MumeiResult<Vec<Artifact>> {
        let signature = emit_atom.signature;
        let contract = emit_atom.contract;
        // Sanitize qualified names (e.g., "MyStruct::my_method" → "MyStruct_my_method")
        // to produce valid Python identifiers, matching CHeaderEmitter behavior.
        let fn_name = signature.name.replace("::", "_");
        let mut py = String::new();

        // Module header
        py.push_str("# Auto-generated by mumei PythonWrapperEmitter\n");
        py.push_str("# FFI glue code — NOT transpiled mumei source.\n");
        py.push_str("# This file provides Python wrappers around a compiled mumei binary.\n\n");

        // Module docstring with contracts
        py.push_str(&format!(
            "\"\"\"\nFFI wrapper for verified atom `{}`.\n\n",
            signature.name
        ));
        if contract.requires_text != "true" {
            py.push_str(&format!("Precondition: {}\n", contract.requires_text));
        }
        if contract.ensures_text != "true" {
            py.push_str(&format!("Postcondition: {}\n", contract.ensures_text));
        }
        py.push_str("\"\"\"\n\n");

        // Imports
        py.push_str("import ctypes\n");
        py.push_str("import os\n");
        py.push_str("from ctypes import ");

        // Collect needed ctypes types
        let mut ctypes_needed: Vec<String> = signature
            .params
            .iter()
            .map(|p| {
                let type_name = p.ty.as_deref().unwrap_or("i64");
                let resolved = module_env.resolve_base_type(type_name);
                mumei_type_to_ctypes(&resolved).to_string()
            })
            .collect();
        let ret_type_name = signature.return_type.as_deref().unwrap_or("i64");
        let ret_resolved = module_env.resolve_base_type(ret_type_name);
        let ret_ctype = mumei_type_to_ctypes(&ret_resolved).to_string();
        ctypes_needed.push(ret_ctype.clone());
        // Expand composite ctypes (e.g., "POINTER(c_int64)") into individual imports
        let mut import_names: Vec<String> = Vec::new();
        for ct in &ctypes_needed {
            if ct.starts_with("POINTER(") {
                import_names.push("POINTER".to_string());
                if let Some(inner) = ct
                    .strip_prefix("POINTER(")
                    .and_then(|s| s.strip_suffix(')'))
                {
                    import_names.push(inner.to_string());
                }
            } else {
                import_names.push(ct.clone());
            }
        }
        import_names.sort();
        import_names.dedup();
        py.push_str(&import_names.join(", "));
        py.push_str("\n\n");

        // Library loading
        py.push_str("# Load the compiled mumei binary.\n");
        py.push_str("# Adjust the path to your compiled .so/.dll/.dylib as needed.\n");
        py.push_str("_LIB_PATH = os.environ.get(\"MUMEI_LIB_PATH\", \"./libmumei.so\")\n");
        py.push_str("_lib = ctypes.CDLL(_LIB_PATH)\n\n");

        // Build parameter info
        let params: Vec<(String, String, String)> = signature
            .params
            .iter()
            .map(|p| {
                let type_name = p.ty.as_deref().unwrap_or("i64");
                let resolved = module_env.resolve_base_type(type_name);
                let ctype = mumei_type_to_ctypes(&resolved).to_string();
                let annotation = mumei_type_to_python_annotation(&resolved).to_string();
                // `consume`/`ref` are mumei ownership markers — emit the bare
                // name in host code.
                (p.name.clone(), ctype, annotation)
            })
            .collect();

        let ret_annotation = mumei_type_to_python_annotation(&ret_resolved);

        // Configure ctypes argtypes and restype
        py.push_str(&format!("_lib.{}.argtypes = [", fn_name));
        let argtypes: Vec<String> = params.iter().map(|(_, ctype, _)| ctype.clone()).collect();
        py.push_str(&argtypes.join(", "));
        py.push_str("]\n");
        py.push_str(&format!("_lib.{}.restype = {}\n\n", fn_name, ret_ctype));

        // Python wrapper function
        let fn_params: Vec<String> = params
            .iter()
            .map(|(name, _, annotation)| format!("{}: {}", name, annotation))
            .collect();
        py.push_str(&format!(
            "def {}({}) -> {}:\n",
            fn_name,
            fn_params.join(", "),
            ret_annotation
        ));

        // Docstring
        py.push_str(&format!(
            "    \"\"\"Safe wrapper for verified atom `{}`.\n\n",
            signature.name
        ));
        py.push_str("    Calls into a compiled mumei binary via ctypes FFI.\n");
        py.push_str("    Preconditions are checked at runtime via assert.\n");
        if contract.requires_text != "true" {
            py.push_str(&format!("\n    Precondition: {}\n", contract.requires_text));
        }
        if contract.ensures_text != "true" {
            py.push_str(&format!("    Postcondition: {}\n", contract.ensures_text));
        }
        py.push_str("    \"\"\"\n");

        // Variable kinds for contract translation (`/` vs `//`, etc.).
        let vars = ContractVars::from_signature(signature, Some(module_env));

        // Runtime precondition check
        if contract.requires_text != "true" {
            match translate_contract_to_python(&contract.requires_text, &vars) {
                Some(cond) => py.push_str(&format!(
                    "    assert {}, \"precondition violated: {}\"\n",
                    cond,
                    escape_message(&contract.requires_text)
                )),
                None => py.push_str(&format!(
                    "    # mumei: requires not expressible as a Python runtime check; left to verification: {}\n",
                    contract.requires_text
                )),
            }
        }
        // Hoisted `forall`/`exists` requires conjuncts: assert each as its own
        // line (`all(cond for v in range(start, end))` / `any(...)`).
        for quantifier in &contract.quantifiers {
            let source = quantifier_source_text(quantifier);
            match quantifier_to_host(quantifier, &vars, HostTarget::Python) {
                Some(cond) => py.push_str(&format!(
                    "    assert {}, \"precondition violated: {}\"\n",
                    cond,
                    escape_message(&source)
                )),
                None => py.push_str(&format!(
                    "    # mumei: quantified requires not expressible as a Python runtime check; left to verification: {}\n",
                    source
                )),
            }
        }

        // FFI call
        let call_args: Vec<String> = params.iter().map(|(name, _, _)| name.clone()).collect();
        py.push_str(&format!(
            "    result = _lib.{}({})\n",
            fn_name,
            call_args.join(", ")
        ));

        // Runtime postcondition check
        if contract.ensures_text != "true" {
            match translate_contract_to_python(&contract.ensures_text, &vars) {
                Some(cond) => py.push_str(&format!(
                    "    assert {}, \"postcondition violated: {}\"\n",
                    cond,
                    escape_message(&contract.ensures_text)
                )),
                None => py.push_str(&format!(
                    "    # mumei: ensures not expressible as a Python runtime check; left to verification: {}\n",
                    contract.ensures_text
                )),
            }
        }

        py.push_str("    return result\n");

        let py_path = output_path.with_extension("py");

        Ok(vec![Artifact {
            name: py_path,
            data: py.into_bytes(),
            kind: ArtifactKind::Source,
        }])
    }
}

/// Escape a contract source string for use inside a `"..."` assert message.
/// Backslashes must be escaped before quotes — quoting first would turn an
/// already-escaped `\"` into `\\\"` and break the string literal.
fn escape_message(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Translate a mumei contract expression to a Python expression.
///
/// This is now AST-based (`mumei_core::contract_host`): `=>` prints as
/// `not a or b`, `/` between integers prints as `//` (floor division, matching
/// the verifier's Z3 Int lowering), `!`/`!=`/`&&`/`||`/`forall`/`exists` and
/// literals are all handled structurally. Returns `None` for clauses with no
/// runtime-checkable Python form — the caller emits a degrade comment instead
/// of invalid code.
fn translate_contract_to_python(contract: &str, vars: &ContractVars) -> Option<String> {
    contract_text_to_host(contract, vars, HostTarget::Python)
}

#[cfg(test)]
mod tests {
    use super::*;
    use mumei_core::hir::{lower_atom_metadata, HirAtom, HirEffectSet, HirExpr, HirStmt};
    use mumei_core::parser::ast::{
        Atom, Expr, Param, Quantifier, QuantifierType, Span, Stmt, TrustLevel,
    };
    use mumei_core::verification::ModuleEnv;

    fn make_param(name: &str, type_name: &str) -> Param {
        Param {
            name: name.to_string(),
            type_name: Some(type_name.to_string()),
            type_ref: None,
            is_ref: false,
            is_ref_mut: false,
            fn_contract_requires: None,
            fn_contract_ensures: None,
        }
    }

    fn make_hir_atom(
        name: &str,
        params: Vec<Param>,
        requires: &str,
        ensures: &str,
        return_type: Option<&str>,
    ) -> HirAtom {
        let body = HirStmt::Expr(HirExpr::Number(0));
        let atom = Atom {
            name: name.to_string(),
            type_params: vec![],
            where_bounds: vec![],
            params,
            trace_id: None,
            spec_metadata: std::collections::HashMap::new(),
            clause_labels: Vec::new(),
            clause_modes: Vec::new(),
            covers: Vec::new(),
            requires: requires.to_string(),
            forall_constraints: vec![],
            ensures: ensures.to_string(),
            body_expr: "0".to_string(),
            consumed_params: vec![],
            resources: vec![],
            is_async: false,
            trust_level: TrustLevel::Verified,
            max_unroll: None,
            invariant: None,
            effects: vec![],
            return_type: return_type.map(|s| s.to_string()),
            decreases: None,
            span: Span::default(),
            effect_pre: std::collections::HashMap::new(),
            effect_post: std::collections::HashMap::new(),
        };
        let (signature, contract, meta) = lower_atom_metadata(&atom, &body, None);
        HirAtom {
            body,
            signature,
            contract,
            meta,
            atom,
            body_stmt: Stmt::Expr(Expr::Number(0), Span::default()),
            effect_set: HirEffectSet::default(),
        }
    }

    fn make_hir_atom_with_quantifiers(
        name: &str,
        params: Vec<Param>,
        requires: &str,
        quantifiers: Vec<Quantifier>,
        ensures: &str,
        return_type: Option<&str>,
    ) -> HirAtom {
        let mut hir = make_hir_atom(name, params, requires, ensures, return_type);
        hir.atom.forall_constraints = quantifiers.clone();
        hir.contract.quantifiers = quantifiers
            .iter()
            .map(|q| {
                let condition_expr = mumei_core::parser::parse_expression_checked(&q.condition)
                    .ok()
                    .map(|e| mumei_core::hir::lower_expr_with_env(&e, None));
                mumei_core::hir::HirQuantifier {
                    kind: if q.q_type == QuantifierType::Exists {
                        mumei_core::hir::HirQuantifierKind::Exists
                    } else {
                        mumei_core::hir::HirQuantifierKind::ForAll
                    },
                    var: q.var.clone(),
                    start: q.start.clone(),
                    end: q.end.clone(),
                    condition: q.condition.clone(),
                    condition_expr,
                }
            })
            .collect();
        hir
    }

    #[test]
    fn test_python_wrapper_quantified_requires_become_runtime_checks() {
        // The parser hoists top-level `forall(`/`exists(` conjuncts out of the
        // requires text into `contract.quantifiers`; each must still become its
        // own assert line ([start, end) — end exclusive, matching `range`).
        let hir = make_hir_atom_with_quantifiers(
            "bounded",
            vec![make_param("x", "i64"), make_param("n", "i64")],
            "x >= 0 && true",
            vec![
                Quantifier {
                    q_type: QuantifierType::ForAll,
                    var: "i".to_string(),
                    start: "0".to_string(),
                    end: "n".to_string(),
                    condition: "i >= 0 && i < x".to_string(),
                },
                Quantifier {
                    q_type: QuantifierType::Exists,
                    var: "j".to_string(),
                    start: "0".to_string(),
                    end: "n".to_string(),
                    condition: "j == 0".to_string(),
                },
            ],
            "result >= 0",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = PythonWrapperEmitter
            .emit(
                &hir.emit_view(),
                Path::new("/tmp/bounded"),
                &module_env,
                &[],
            )
            .unwrap();
        let py = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(
            py.contains(
                "assert all(i >= 0 and i < x for i in range(0, n)), \"precondition violated: forall(i, 0, n, i >= 0 && i < x)\""
            ),
            "forall should be an all(...) runtime check:\n{py}"
        );
        assert!(
            py.contains(
                "assert any(j == 0 for j in range(0, n)), \"precondition violated: exists(j, 0, n, j == 0)\""
            ),
            "exists should be an any(...) runtime check:\n{py}"
        );
    }

    #[test]
    fn test_python_wrapper_untranslatable_quantifier_degrades_to_comment() {
        let hir = make_hir_atom_with_quantifiers(
            "weird",
            vec![make_param("x", "i64")],
            "x >= 0 && true",
            vec![Quantifier {
                q_type: QuantifierType::ForAll,
                var: "i".to_string(),
                start: "0".to_string(),
                end: "x".to_string(),
                condition: "match i { _ => true }".to_string(),
            }],
            "result >= 0",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = PythonWrapperEmitter
            .emit(&hir.emit_view(), Path::new("/tmp/weird"), &module_env, &[])
            .unwrap();
        let py = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(
            py.contains("# mumei: quantified requires not expressible as a Python runtime check"),
            "untranslatable quantifier should degrade to a comment:\n{py}"
        );
        assert!(py.contains("def weird("), "wrapper still emitted:\n{py}");
    }

    #[test]
    fn test_python_wrapper_basic() {
        let hir = make_hir_atom(
            "safe_add",
            vec![make_param("a", "i64"), make_param("b", "i64")],
            "a >= 0 && b >= 0",
            "result == a + b",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = PythonWrapperEmitter
            .emit(
                &hir.emit_view(),
                Path::new("/tmp/safe_add"),
                &module_env,
                &[],
            )
            .unwrap();

        assert_eq!(artifacts.len(), 1);
        assert_eq!(
            artifacts[0].name,
            std::path::PathBuf::from("/tmp/safe_add.py")
        );
        assert_eq!(artifacts[0].kind, ArtifactKind::Source);

        let py = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(py.contains("import ctypes"));
        assert!(py.contains("from ctypes import"));
        assert!(py.contains("def safe_add("));
        assert!(py.contains("a: int, b: int"));
        assert!(py.contains("-> int"));
        assert!(py.contains("assert a >= 0 and b >= 0"));
        assert!(py.contains("_lib.safe_add(a, b)"));
        assert!(py.contains("NOT transpiled mumei source"));
    }

    #[test]
    fn test_python_wrapper_no_contracts() {
        let hir = make_hir_atom(
            "identity",
            vec![make_param("x", "i64")],
            "true",
            "true",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = PythonWrapperEmitter
            .emit(
                &hir.emit_view(),
                Path::new("/tmp/identity"),
                &module_env,
                &[],
            )
            .unwrap();

        let py = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(!py.contains("assert "));
        assert!(py.contains("def identity(x: int) -> int:"));
    }

    #[test]
    fn test_contract_translation() {
        let vars = ContractVars::new();
        let tr = |s: &str| translate_contract_to_python(s, &vars);
        assert_eq!(tr("a >= 0 && b >= 0").as_deref(), Some("a >= 0 and b >= 0"));
        assert_eq!(tr("x > 0 || y > 0").as_deref(), Some("x > 0 or y > 0"));
        assert_eq!(tr("result == 42").as_deref(), Some("result == 42"));
        // Negation: ! → not (Python `not` binds looser than comparisons)
        assert_eq!(tr("!(x < 0)").as_deref(), Some("not x < 0"));
        // != must be preserved
        assert_eq!(tr("x != 0").as_deref(), Some("x != 0"));
        // Combined: negation + !=
        assert_eq!(tr("!(x != 0)").as_deref(), Some("not x != 0"));
        // Boolean literals: true/false → True/False
        assert_eq!(tr("result == true").as_deref(), Some("result == True"));
        assert_eq!(
            tr("result == false || x > 0").as_deref(),
            Some("result == False or x > 0")
        );
        // `=>` implication → `not a or b`, operands parenthesized
        assert_eq!(
            tr("x > 0 => result > 0").as_deref(),
            Some("not (x > 0) or (result > 0)")
        );
        // `=>` inside a larger expression (`=>` binds looser than `||`)
        assert_eq!(
            tr("x > 0 || y > 0 => z > 0").as_deref(),
            Some("not (x > 0 or y > 0) or (z > 0)")
        );
        // Chained `=>` is left-associative: (a => b) => c
        assert_eq!(
            tr("a > 0 => b > 0 => c > 0").as_deref(),
            Some("not (not (a > 0) or (b > 0)) or (c > 0)")
        );
        // `/` between ints → Euclidean division matching Z3 `Int` semantics
        // (remainder ≥ 0): `divmod` quotient + 1 when the floored remainder
        // went negative. divmod+walrus evaluates each operand once, so
        // chained divisions emit linear text.
        assert_eq!(
            tr("a / b >= 0").as_deref(),
            Some("((_mumei_d := divmod(a, b))[0] + (_mumei_d[1] < 0)) >= 0")
        );
        // Quantifiers nested inside an expression still translate
        assert_eq!(
            tr("n <= 0 || forall(i, 0, n, i >= 0)").as_deref(),
            Some("n <= 0 or all(i >= 0 for i in range(0, n))")
        );
        // Unparseable tail degrades to None instead of emitting broken Python
        assert_eq!(tr("result >= 0 -> result < 10"), None);
        // Negative literals stay parenthesized under `**`
        // (`-2 ** 2` would evaluate to -4 in Python).
        assert_eq!(tr("-2 ** 2 == 4").as_deref(), Some("(-2) ** 2 == 4"));
        // `::`-qualified names mangle to FFI symbols, never host paths
        assert_eq!(tr("Vec2::dot(x) >= 0").as_deref(), Some("Vec2_dot(x) >= 0"));
        // Pointer indexing / field reads degrade: they would dereference
        // unvalidated FFI data inside a nominally safe wrapper.
        assert_eq!(tr("arr[i] >= 0"), None);
        assert_eq!(tr("v.x >= 0"), None);
        assert_eq!(tr("forall(i, 0, n, arr[i] >= 0)"), None);
        // ...but a translatable conjunct alongside them is still enforced:
        // only the untranslatable conjunct drops.
        assert_eq!(
            tr("n > 0 && arr[i] > 0 && result >= 0").as_deref(),
            Some("n > 0 and result >= 0")
        );
    }

    #[test]
    fn test_contract_translation_negative_division() {
        // Z3 `Int` division is EUCLIDEAN (remainder ≥ 0), not floor: verified
        // `div(7,-2) = -3`, `div(-7,-2) = 4`, `div(-7,2) = -4`. The emitted
        // `divmod(l,r)[0] + (divmod(l,r)[1] < 0)` adds 1 exactly when the
        // floored remainder went negative — only possible under a negative
        // divisor — matching Z3 for all sign combinations.
        let vars = ContractVars::new();
        assert_eq!(
            translate_contract_to_python("0 - a / b <= result", &vars).as_deref(),
            Some("0 - ((_mumei_d := divmod(a, b))[0] + (_mumei_d[1] < 0)) <= result")
        );
        // `(-7) / 2`: divmod gives (-4, 1); remainder ≥ 0 → result stays -4
        // — Z3 `div(-7, 2) == -4`.
        assert_eq!(
            translate_contract_to_python("(0 - 7) / 2 == 0 - 4", &vars).as_deref(),
            Some("((_mumei_d := divmod(0 - 7, 2))[0] + (_mumei_d[1] < 0)) == 0 - 4")
        );
        // Negative divisor: `7 / (0 - 2)` → divmod gives (-4, -1) →
        // `-4 + 1 == -3` — Z3 `div(7, -2) == -3` (plain `//` would mischeck
        // a verified clause here).
        assert_eq!(
            translate_contract_to_python("7 / (0 - 2) == 0 - 3", &vars).as_deref(),
            Some("((_mumei_d := divmod(7, 0 - 2))[0] + (_mumei_d[1] < 0)) == 0 - 3")
        );
        // Chained divisions stay linear: operands are evaluated once via
        // divmod instead of being printed twice per level.
        assert_eq!(
            translate_contract_to_python("a / b / c >= 0", &vars).as_deref(),
            Some(
                "((_mumei_d := divmod(((_mumei_d := divmod(a, b))[0] + (_mumei_d[1] < 0)), c))[0] + (_mumei_d[1] < 0)) >= 0"
            )
        );
        // Float operands keep `/`.
        let mut fvars = ContractVars::new();
        fvars.insert("fa", mumei_core::contract_host::ContractVarKind::Float);
        fvars.insert("fb", mumei_core::contract_host::ContractVarKind::Float);
        assert_eq!(
            translate_contract_to_python("fa / fb > 0.5", &fvars).as_deref(),
            Some("fa / fb > 0.5")
        );
    }

    #[test]
    fn test_type_mapping_array_edge_cases() {
        assert_eq!(mumei_type_to_ctypes("[f64]"), "c_int64");
        assert_eq!(mumei_type_to_python_annotation("[[i64]]"), "int");
    }

    #[test]
    fn test_type_mapping() {
        assert_eq!(mumei_type_to_ctypes("i64"), "c_int64");
        assert_eq!(mumei_type_to_ctypes("i32"), "c_int32");
        assert_eq!(mumei_type_to_ctypes("u64"), "c_uint64");
        assert_eq!(mumei_type_to_ctypes("bool"), "c_int64");
        assert_eq!(mumei_type_to_ctypes("Str"), "c_char_p");
        assert_eq!(mumei_type_to_ctypes("[i64]"), "POINTER(c_int64)");
        assert_eq!(mumei_type_to_ctypes("UnknownType"), "c_int64");
    }

    #[test]
    fn test_python_annotation_mapping() {
        assert_eq!(mumei_type_to_python_annotation("i64"), "int");
        assert_eq!(mumei_type_to_python_annotation("f64"), "float");
        assert_eq!(mumei_type_to_python_annotation("bool"), "bool");
        assert_eq!(mumei_type_to_python_annotation("Str"), "bytes");
    }
}
