//! FFI glue code generator for Python.
//!
//! **NOT a transpiler** — this emitter does NOT convert mumei code into Python.
//! It generates `ctypes`-based Python wrapper functions that call compiled mumei
//! binaries (`.so`/`.dll`) via FFI. This is the same layer as `CHeaderEmitter`
//! (which generates `.h` files).
//!
//! The generated `.py` file contains:
//! - Module docstring with contracts
//! - `ctypes` imports and library loading boilerplate
//! - Type-annotated Python functions with `assert` for requires

use mumei_core::emitter::{Artifact, ArtifactKind, Emitter};
use mumei_core::hir::HirAtom;
use mumei_core::parser::ExternBlock;
use mumei_core::verification::{ModuleEnv, MumeiResult};
use std::path::Path;

/// Map a mumei type name to its Python ctypes equivalent.
fn mumei_type_to_ctypes(type_name: &str) -> &str {
    match type_name {
        "i64" => "c_int64",
        "i32" => "c_int32",
        "u64" => "c_uint64",
        "u32" => "c_uint32",
        "f64" => "c_double",
        "f32" => "c_float",
        "bool" => "c_int64", // mumei compiles bool to i64 in LLVM IR
        "Str" | "String" => "c_char_p",
        _ => "c_int64", // default fallback for refined types based on i64
    }
}

/// Map a mumei type name to its Python type annotation.
fn mumei_type_to_python_annotation(type_name: &str) -> &str {
    match type_name {
        "i64" | "i32" | "u64" | "u32" => "int",
        "f64" | "f32" => "float",
        "bool" => "bool",
        "Str" | "String" => "bytes",
        _ => "int",
    }
}

/// FFI glue code generator for Python.
///
/// Generates `ctypes`-based Python wrapper functions that call compiled
/// mumei binaries via FFI. NOT a transpiler.
pub struct PythonWrapperEmitter;

impl Emitter for PythonWrapperEmitter {
    fn emit(
        &self,
        hir_atom: &HirAtom,
        output_path: &Path,
        module_env: &ModuleEnv,
        _extern_blocks: &[ExternBlock],
    ) -> MumeiResult<Vec<Artifact>> {
        let atom = &hir_atom.atom;
        // Sanitize qualified names (e.g., "MyStruct::my_method" → "MyStruct__my_method")
        // to produce valid Python identifiers, matching CHeaderEmitter behavior.
        let fn_name = atom.name.replace("::", "__");
        let mut py = String::new();

        // Module header
        py.push_str("# Auto-generated by mumei PythonWrapperEmitter\n");
        py.push_str("# FFI glue code — NOT transpiled mumei source.\n");
        py.push_str("# This file provides Python wrappers around a compiled mumei binary.\n\n");

        // Module docstring with contracts
        py.push_str(&format!(
            "\"\"\"\nFFI wrapper for verified atom `{}`.\n\n",
            atom.name
        ));
        if atom.requires != "true" {
            py.push_str(&format!("Precondition: {}\n", atom.requires));
        }
        if atom.ensures != "true" {
            py.push_str(&format!("Postcondition: {}\n", atom.ensures));
        }
        py.push_str("\"\"\"\n\n");

        // Imports
        py.push_str("import ctypes\n");
        py.push_str("import os\n");
        py.push_str("from ctypes import ");

        // Collect needed ctypes types
        let mut ctypes_needed: Vec<String> = atom
            .params
            .iter()
            .map(|p| {
                let type_name = p.type_name.as_deref().unwrap_or("i64");
                let resolved = module_env.resolve_base_type(type_name);
                mumei_type_to_ctypes(&resolved).to_string()
            })
            .collect();
        let ret_type_name = atom.return_type.as_deref().unwrap_or("i64");
        let ret_resolved = module_env.resolve_base_type(ret_type_name);
        let ret_ctype = mumei_type_to_ctypes(&ret_resolved).to_string();
        ctypes_needed.push(ret_ctype.clone());
        ctypes_needed.sort();
        ctypes_needed.dedup();
        py.push_str(&ctypes_needed.join(", "));
        py.push_str("\n\n");

        // Library loading
        py.push_str("# Load the compiled mumei binary.\n");
        py.push_str("# Adjust the path to your compiled .so/.dll/.dylib as needed.\n");
        py.push_str(&format!(
            "_LIB_PATH = os.environ.get(\"MUMEI_LIB_PATH\", \"./libmumei.so\")\n"
        ));
        py.push_str("_lib = ctypes.CDLL(_LIB_PATH)\n\n");

        // Build parameter info
        let params: Vec<(String, String, String)> = atom
            .params
            .iter()
            .map(|p| {
                let type_name = p.type_name.as_deref().unwrap_or("i64");
                let resolved = module_env.resolve_base_type(type_name);
                let ctype = mumei_type_to_ctypes(&resolved).to_string();
                let annotation = mumei_type_to_python_annotation(&resolved).to_string();
                (p.name.clone(), ctype, annotation)
            })
            .collect();

        let ret_annotation = mumei_type_to_python_annotation(&ret_resolved);

        // Configure ctypes argtypes and restype
        py.push_str(&format!("_lib.{}.argtypes = [", fn_name));
        let argtypes: Vec<String> = params.iter().map(|(_, ctype, _)| ctype.clone()).collect();
        py.push_str(&argtypes.join(", "));
        py.push_str("]\n");
        py.push_str(&format!("_lib.{}.restype = {}\n\n", fn_name, ret_ctype));

        // Python wrapper function
        let fn_params: Vec<String> = params
            .iter()
            .map(|(name, _, annotation)| format!("{}: {}", name, annotation))
            .collect();
        py.push_str(&format!(
            "def {}({}) -> {}:\n",
            fn_name,
            fn_params.join(", "),
            ret_annotation
        ));

        // Docstring
        py.push_str(&format!(
            "    \"\"\"Safe wrapper for verified atom `{}`.\n\n",
            atom.name
        ));
        py.push_str("    Calls into a compiled mumei binary via ctypes FFI.\n");
        py.push_str("    Preconditions are checked at runtime via assert.\n");
        if atom.requires != "true" {
            py.push_str(&format!("\n    Precondition: {}\n", atom.requires));
        }
        if atom.ensures != "true" {
            py.push_str(&format!("    Postcondition: {}\n", atom.ensures));
        }
        py.push_str("    \"\"\"\n");

        // Runtime precondition check
        if atom.requires != "true" {
            py.push_str(&format!(
                "    assert {}, \"precondition violated: {}\"\n",
                translate_contract_to_python(&atom.requires),
                atom.requires.replace('"', "\\\"")
            ));
        }

        // FFI call
        let call_args: Vec<String> = params.iter().map(|(name, _, _)| name.clone()).collect();
        py.push_str(&format!(
            "    result = _lib.{}({})\n",
            fn_name,
            call_args.join(", ")
        ));

        // Runtime postcondition check
        if atom.ensures != "true" {
            py.push_str(&format!(
                "    assert {}, \"postcondition violated: {}\"\n",
                translate_contract_to_python(&atom.ensures),
                atom.ensures.replace('"', "\\\"")
            ));
        }

        py.push_str("    return result\n");

        let py_path = output_path.with_extension("py");

        Ok(vec![Artifact {
            name: py_path,
            data: py.into_bytes(),
            kind: ArtifactKind::Source,
        }])
    }
}

/// Translate a mumei contract expression to valid Python syntax.
///
/// Handles common patterns:
/// - `&&` → `and`
/// - `||` → `or`
/// - `!` (prefix negation) → `not `
/// - `!=` is preserved (not affected by `!` replacement)
/// - `result` → kept as-is (local variable in wrapper)
///
/// NOTE: `=>` (implication) is not yet handled and will produce invalid Python.
fn translate_contract_to_python(contract: &str) -> String {
    // First replace multi-char operators to avoid partial matches
    let result = contract.replace("&&", " and ").replace("||", " or ");
    // Replace `!=` with a placeholder, then `!` with `not `, then restore `!=`
    let result = result
        .replace("!=", "\x00NEQ\x00")
        .replace('!', "not ")
        .replace("\x00NEQ\x00", "!=");
    // Normalize whitespace (collapse multiple spaces)
    result
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use mumei_core::hir::{HirEffectSet, HirExpr, HirStmt};
    use mumei_core::parser::ast::{Atom, Expr, Param, Span, Stmt, TrustLevel};
    use mumei_core::verification::ModuleEnv;

    fn make_param(name: &str, type_name: &str) -> Param {
        Param {
            name: name.to_string(),
            type_name: Some(type_name.to_string()),
            type_ref: None,
            is_ref: false,
            is_ref_mut: false,
            fn_contract_requires: None,
            fn_contract_ensures: None,
        }
    }

    fn make_hir_atom(
        name: &str,
        params: Vec<Param>,
        requires: &str,
        ensures: &str,
        return_type: Option<&str>,
    ) -> HirAtom {
        HirAtom {
            body: HirStmt::Expr(HirExpr::Number(0)),
            requires_hir: HirExpr::Number(1),
            ensures_hir: HirExpr::Number(1),
            atom: Atom {
                name: name.to_string(),
                type_params: vec![],
                where_bounds: vec![],
                params,
                requires: requires.to_string(),
                forall_constraints: vec![],
                ensures: ensures.to_string(),
                body_expr: "0".to_string(),
                consumed_params: vec![],
                resources: vec![],
                is_async: false,
                trust_level: TrustLevel::Verified,
                max_unroll: None,
                invariant: None,
                effects: vec![],
                return_type: return_type.map(|s| s.to_string()),
                span: Span::default(),
                effect_pre: std::collections::HashMap::new(),
                effect_post: std::collections::HashMap::new(),
            },
            body_stmt: Stmt::Expr(Expr::Number(0), Span::default()),
            effect_set: HirEffectSet::default(),
        }
    }

    #[test]
    fn test_python_wrapper_basic() {
        let hir = make_hir_atom(
            "safe_add",
            vec![make_param("a", "i64"), make_param("b", "i64")],
            "a >= 0 && b >= 0",
            "result == a + b",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = PythonWrapperEmitter
            .emit(&hir, Path::new("/tmp/safe_add"), &module_env, &[])
            .unwrap();

        assert_eq!(artifacts.len(), 1);
        assert_eq!(
            artifacts[0].name,
            std::path::PathBuf::from("/tmp/safe_add.py")
        );
        assert_eq!(artifacts[0].kind, ArtifactKind::Source);

        let py = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(py.contains("import ctypes"));
        assert!(py.contains("from ctypes import"));
        assert!(py.contains("def safe_add("));
        assert!(py.contains("a: int, b: int"));
        assert!(py.contains("-> int"));
        assert!(py.contains("assert a >= 0 and b >= 0"));
        assert!(py.contains("_lib.safe_add(a, b)"));
        assert!(py.contains("NOT transpiled mumei source"));
    }

    #[test]
    fn test_python_wrapper_no_contracts() {
        let hir = make_hir_atom(
            "identity",
            vec![make_param("x", "i64")],
            "true",
            "true",
            Some("i64"),
        );
        let module_env = ModuleEnv::new();
        let artifacts = PythonWrapperEmitter
            .emit(&hir, Path::new("/tmp/identity"), &module_env, &[])
            .unwrap();

        let py = String::from_utf8(artifacts[0].data.clone()).unwrap();
        assert!(!py.contains("assert "));
        assert!(py.contains("def identity(x: int) -> int:"));
    }

    #[test]
    fn test_contract_translation() {
        assert_eq!(
            translate_contract_to_python("a >= 0 && b >= 0"),
            "a >= 0 and b >= 0"
        );
        assert_eq!(
            translate_contract_to_python("x > 0 || y > 0"),
            "x > 0 or y > 0"
        );
        assert_eq!(translate_contract_to_python("result == 42"), "result == 42");
        // Negation: ! → not
        assert_eq!(
            translate_contract_to_python("!(x < 0)"),
            "not (x < 0)"
        );
        // != must be preserved
        assert_eq!(
            translate_contract_to_python("x != 0"),
            "x != 0"
        );
        // Combined: negation + !=
        assert_eq!(
            translate_contract_to_python("!(x != 0)"),
            "not (x != 0)"
        );
    }

    #[test]
    fn test_type_mapping() {
        assert_eq!(mumei_type_to_ctypes("i64"), "c_int64");
        assert_eq!(mumei_type_to_ctypes("i32"), "c_int32");
        assert_eq!(mumei_type_to_ctypes("u64"), "c_uint64");
        assert_eq!(mumei_type_to_ctypes("bool"), "c_int64");
        assert_eq!(mumei_type_to_ctypes("Str"), "c_char_p");
        assert_eq!(mumei_type_to_ctypes("UnknownType"), "c_int64");
    }

    #[test]
    fn test_python_annotation_mapping() {
        assert_eq!(mumei_type_to_python_annotation("i64"), "int");
        assert_eq!(mumei_type_to_python_annotation("f64"), "float");
        assert_eq!(mumei_type_to_python_annotation("bool"), "bool");
        assert_eq!(mumei_type_to_python_annotation("Str"), "bytes");
    }
}
