// Auto-generated by mumei RuntimeMonitorEmitter (proof-aware observability).
// Only trust boundaries are instrumented; fully proven atoms emit no code.

/// Runtime support for mumei proof-aware monitors.
///
/// Reporting is a no-op unless `OTEL_ENABLED` is truthy. When enabled, the
/// violation is forwarded to the hook installed via `set_violation_hook`
/// (wire this to your OpenTelemetry SDK); the default hook writes to stderr
/// and names the configured `OTEL_EXPORTER_OTLP_ENDPOINT`.
pub mod mumei_monitor {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::OnceLock;

    /// A single observed contract violation at a trust boundary.
    #[derive(Debug, Clone)]
    pub struct Violation {
        pub atom: &'static str,
        pub boundary: &'static str,
        pub contract: &'static str,
        pub expression: &'static str,
        /// Effect state the host reported, for `effect_pre` violations.
        pub observed: Option<String>,
    }

    type Hook = fn(&Violation);
    /// Reports the effect state the host currently observes, if it tracks one.
    type EffectStateProbe = fn(&str) -> Option<String>;

    static HOOK: OnceLock<Hook> = OnceLock::new();
    static PROBE: OnceLock<EffectStateProbe> = OnceLock::new();
    static ENABLED: OnceLock<bool> = OnceLock::new();
    static WARNED: AtomicBool = AtomicBool::new(false);

    /// Install the OTel reporting hook. Call once during startup.
    pub fn set_violation_hook(hook: Hook) -> Result<(), &'static str> {
        HOOK.set(hook).map_err(|_| "violation hook already installed")
    }

    /// Install the effect-state probe. Without it the runtime effect state is
    /// unobservable, so `effect_pre` assumptions are left unchecked.
    pub fn set_effect_state_probe(probe: EffectStateProbe) -> Result<(), &'static str> {
        PROBE
            .set(probe)
            .map_err(|_| "effect state probe already installed")
    }

    /// The host's current state for `effect`, or `None` when untracked.
    ///
    /// A faulty probe must not unwind through monitored code, so a panicking
    /// probe is treated as "state unobservable".
    pub fn observed_effect_state(effect: &str) -> Option<String> {
        PROBE.get().and_then(|probe| {
            match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| probe(effect))) {
                Ok(state) => state,
                Err(_) => {
                    eprintln!("mumei.monitor.probe_panicked effect={}", effect);
                    None
                }
            }
        })
    }

    /// `true` when `OTEL_ENABLED` is truthy; otherwise monitors are no-ops.
    pub fn enabled() -> bool {
        *ENABLED.get_or_init(|| {
            matches!(
                std::env::var("OTEL_ENABLED")
                    .unwrap_or_default()
                    .to_ascii_lowercase()
                    .as_str(),
                "1" | "true" | "yes" | "on"
            )
        })
    }

    /// OTLP endpoint the default hook reports against.
    pub fn endpoint() -> String {
        std::env::var("OTEL_EXPORTER_OTLP_ENDPOINT")
            .unwrap_or_else(|_| "http://localhost:4318".to_string())
    }

    fn default_hook(violation: &Violation) {
        if !WARNED.swap(true, Ordering::Relaxed) {
            eprintln!(
                "mumei.monitor: no violation hook installed; reporting to stderr instead of {}",
                endpoint()
            );
        }
        eprintln!(
            "mumei.monitor.contract_violation atom={} boundary={} contract={} expression={} observed={}",
            violation.atom,
            violation.boundary,
            violation.contract,
            violation.expression,
            violation.observed.as_deref().unwrap_or("-")
        );
    }

    /// Record a violation. Never panics — the proof-aware monitor observes,
    /// it does not abort the program.
    pub fn record(violation: Violation) {
        if !enabled() {
            return;
        }
        let reported = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            match HOOK.get() {
                Some(hook) => hook(&violation),
                None => default_hook(&violation),
            }
        }));
        if reported.is_err() {
            // A faulty host hook must not unwind through monitored code.
            eprintln!(
                "mumei.monitor.hook_panicked atom={} boundary={} contract={}",
                violation.atom, violation.boundary, violation.contract
            );
        }
    }

    /// Evaluate a contract without letting it unwind into the monitored call.
    ///
    /// A contract may divide by zero or overflow in a debug build, which would
    /// abort the very call the monitor only observes. Such an evaluation is
    /// reported as `observed = "evaluation panicked"` instead.
    pub fn check(violation: Violation, condition: impl FnOnce() -> bool) {
        if !enabled() {
            return;
        }
        match std::panic::catch_unwind(std::panic::AssertUnwindSafe(condition)) {
            Ok(true) => {}
            Ok(false) => record(violation),
            Err(_) => record(Violation {
                observed: Some("evaluation panicked".to_string()),
                ..violation
            }),
        }
    }
}

extern "C" {
    fn assumed_ensures(x: i64) -> i64;
}

/// Monitored trust boundary `assumed_ensures`.
///
/// - assumed_clause: a requires/ensures clause is marked `assume`, so it is trusted rather than checked on one side of the call
///
/// Contract violations are reported as OTel events, never panics.
pub fn assumed_ensures_monitored(x: i64) -> i64 {
    mumei_monitor::check(mumei_monitor::Violation {
            atom: "assumed_ensures",
            boundary: "assumed_clause",
            contract: "requires",
            expression: "x > 0",
            observed: None,
        }, || x > 0);
    let result = unsafe { assumed_ensures(x) };
    mumei_monitor::check(mumei_monitor::Violation {
            atom: "assumed_ensures",
            boundary: "assumed_clause",
            contract: "ensures",
            expression: "(result > 0) && (result < 100)",
            observed: None,
        }, || (result > 0) && (result < 100));
    result
}
