#!/usr/bin/env python3
"""Generate a Homebrew Formula for Mumei.

This script is invoked by the release CI (``.github/workflows/release.yml``)
to regenerate ``Formula/mumei.rb`` in the ``mumei-lang/homebrew-mumei`` tap
whenever a new ``v*`` tag is released.

Extracting the Formula template from an inline YAML heredoc into a dedicated
Python script keeps the Formula content under version control and makes it
trivially testable locally — running the script with a known tag should
reproduce the checked-in Formula byte-for-byte.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

FORMULA_TEMPLATE = '''# Homebrew Formula for Mumei — auto-generated by release workflow
class Mumei < Formula
  desc "Mathematical Proof-Driven Programming Language — formally verified with Z3"
  homepage "https://github.com/mumei-lang/mumei"
  license "Apache-2.0"
  version "{version}"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v{version}/mumei-aarch64-apple-darwin.tar.gz"
      sha256 "{sha_arm_mac}"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v{version}/mumei-x86_64-apple-darwin.tar.gz"
      sha256 "{sha_x86_mac}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v{version}/mumei-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "{sha_arm_linux}"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v{version}/mumei-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "{sha_x86_linux}"
    end
  end

  depends_on "z3"
  depends_on "llvm@17"

  def install
    bin.install "mumei"
    (share/"mumei/std").install Dir["std/*"]

    # SI-5 Phase 3-C: install the std/ proof-certificate bundle when it
    # ships with the release tarball so downstream projects can verify
    # imports against a trusted, versioned certificate set.
    has_proof_bundle = File.exist?("std-proof-bundle.json")
    if has_proof_bundle
      (share/"mumei").install "std-proof-bundle.json"
    end

    env_script = "export MUMEI_STD_PATH=\\"#{{share}}/mumei/std\\"\\n"
    if has_proof_bundle
      env_script += "export MUMEI_PROOF_BUNDLE=\\"#{{share}}/mumei/std-proof-bundle.json\\"\\n"
    end
    (etc/"mumei").mkpath
    (etc/"mumei/env.sh").write env_script
  end

  def caveats
    s = <<~EOS
      The Mumei standard library has been installed to:
        #{{share}}/mumei/std

    EOS
    if (share/"mumei/std-proof-bundle.json").exist?
      s += <<~EOS
        The std/ proof-certificate bundle (SI-5 Phase 3-C) is at:
          #{{share}}/mumei/std-proof-bundle.json

      EOS
    end
    s += <<~EOS
      To use it, add the following to your shell profile:
        export MUMEI_STD_PATH="#{{share}}/mumei/std"
    EOS
    if (share/"mumei/std-proof-bundle.json").exist?
      s += "  export MUMEI_PROOF_BUNDLE=\\"#{{share}}/mumei/std-proof-bundle.json\\"\\n"
    end
    s += <<~EOS

      Or source the environment file:
        source #{{etc}}/mumei/env.sh
    EOS
    s
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/mumei --version")
  end
end
'''


def render_formula(
    version: str,
    sha_x86_mac: str,
    sha_arm_mac: str,
    sha_x86_linux: str,
    sha_arm_linux: str,
) -> str:
    ver = version.lstrip("v")
    return FORMULA_TEMPLATE.format(
        version=ver,
        sha_x86_mac=sha_x86_mac,
        sha_arm_mac=sha_arm_mac,
        sha_x86_linux=sha_x86_linux,
        sha_arm_linux=sha_arm_linux,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--version",
        required=True,
        help="Release version (with or without the leading 'v'), e.g. 0.4.2 or v0.4.2.",
    )
    parser.add_argument(
        "--sha-x86-mac",
        required=True,
        help="sha256 for mumei-x86_64-apple-darwin.tar.gz",
    )
    parser.add_argument(
        "--sha-arm-mac",
        required=True,
        help="sha256 for mumei-aarch64-apple-darwin.tar.gz",
    )
    parser.add_argument(
        "--sha-x86-linux",
        required=True,
        help="sha256 for mumei-x86_64-unknown-linux-gnu.tar.gz",
    )
    parser.add_argument(
        "--sha-arm-linux",
        required=True,
        help="sha256 for mumei-aarch64-unknown-linux-gnu.tar.gz",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Path to write the Formula to. Writes to stdout when omitted.",
    )
    args = parser.parse_args(argv)

    content = render_formula(
        version=args.version,
        sha_x86_mac=args.sha_x86_mac,
        sha_arm_mac=args.sha_arm_mac,
        sha_x86_linux=args.sha_x86_linux,
        sha_arm_linux=args.sha_arm_linux,
    )

    if args.output is None:
        sys.stdout.write(content)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
