"""Generate ``docs/STDLIB_METRICS.md`` from the live state of ``std/``.

SI-5 Phase 3-A (mumei-side completion). For each ``std/*.mm`` file we
compute:

* ``atoms``         — total atom definitions declared in the file
* ``trusted``       — number of ``trusted atom`` declarations (proof holes)
* ``verified``      — whether ``mumei verify`` succeeds (``OK`` / ``FAIL``
  / ``SKIP`` when no mumei binary is available)
* ``todos``         — count of ``TODO`` / ``FIXME`` / ``XXX`` / ``HACK``
  markers in the file
* ``health_score``  — ``(atoms - trusted) / atoms`` with a TODO penalty of
  1% per TODO (capped at 20%). Files without atoms score 1.0.

The resulting table is regenerated by ``.github/workflows/update-metrics.yml``
whenever ``std/**`` changes.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

ATOM_RE = re.compile(r"^\s*(?:trusted\s+|async\s+)?atom\s+\w+")
TRUSTED_ATOM_RE = re.compile(r"^\s*trusted\s+atom\s+\w+")
TODO_RE = re.compile(r"//.*?\b(TODO|FIXME|XXX|HACK)\b", re.IGNORECASE)


def _count_metrics(path: Path) -> tuple[int, int, int]:
    """Return ``(atoms, trusted_atoms, todos)`` for ``path``."""
    atoms = trusted = todos = 0
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return 0, 0, 0
    for line in text.splitlines():
        if ATOM_RE.match(line):
            atoms += 1
        if TRUSTED_ATOM_RE.match(line):
            trusted += 1
        if TODO_RE.search(line):
            todos += 1
    return atoms, trusted, todos


def _run_verify(mumei_bin: Path | None, mm_path: Path) -> str:
    """Return ``OK`` / ``FAIL`` / ``SKIP`` for ``mumei verify <mm_path>``."""
    if mumei_bin is None:
        return "SKIP"
    try:
        proc = subprocess.run(  # noqa: S603 — binary path is caller-provided
            [str(mumei_bin), "verify", str(mm_path)],
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return "SKIP"
    return "OK" if proc.returncode == 0 else "FAIL"


def _compute_health(atoms: int, trusted: int, todos: int, verified: str) -> float:
    if atoms == 0:
        base = 1.0
    else:
        base = max(0.0, (atoms - trusted) / atoms)
    penalty = min(todos * 0.01, 0.2)
    score = base - penalty
    if verified == "FAIL":
        # Failing verification halves the score — a module whose Z3 proofs
        # don't close is fundamentally untrustworthy.
        score *= 0.5
    return round(max(0.0, min(1.0, score)), 3)


def _scan_std(std_dir: Path, mumei_bin: Path | None) -> list[dict]:
    rows: list[dict] = []
    for mm_path in sorted(std_dir.rglob("*.mm")):
        rel = str(mm_path.relative_to(std_dir.parent)).replace("\\", "/")
        atoms, trusted, todos = _count_metrics(mm_path)
        verified = _run_verify(mumei_bin, mm_path)
        rows.append(
            {
                "path": rel,
                "atoms": atoms,
                "trusted": trusted,
                "todos": todos,
                "verified": verified,
                "health": _compute_health(atoms, trusted, todos, verified),
            },
        )
    return rows


def _render_markdown(rows: list[dict]) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_atoms = sum(r["atoms"] for r in rows)
    total_trusted = sum(r["trusted"] for r in rows)
    total_todos = sum(r["todos"] for r in rows)
    fully_verified = sum(1 for r in rows if r["verified"] == "OK")
    failed = sum(1 for r in rows if r["verified"] == "FAIL")
    skipped = sum(1 for r in rows if r["verified"] == "SKIP")
    # Weighted health: atoms as weights.
    weighted_health = (
        round(
            sum(r["health"] * max(1, r["atoms"]) for r in rows)
            / max(1, sum(max(1, r["atoms"]) for r in rows)),
            3,
        )
    )

    lines = [
        "# Mumei std/ Metrics",
        "",
        f"_Auto-generated by `scripts/generate_stdlib_metrics.py` — {generated_at}_",
        "",
        "Part of **SI-5 Phase 3-A**. Measures the health of the verified ",
        "standard library by counting atoms, trusted atoms (proof holes), ",
        "TODO markers and the result of `mumei verify` per module. The CI ",
        "workflow `.github/workflows/update-metrics.yml` keeps this file ",
        "fresh on every push to `std/`.",
        "",
        "## Summary",
        "",
        f"- **Modules:** {len(rows)} ({fully_verified} OK / {failed} FAIL / {skipped} SKIP)",
        f"- **Atoms total:** {total_atoms}",
        f"- **Trusted atoms (proof holes):** {total_trusted}",
        f"- **TODO/FIXME/XXX/HACK markers:** {total_todos}",
        f"- **Weighted health score:** {weighted_health:.3f} / 1.000",
        "",
        "## Per-module breakdown",
        "",
        "| Module | Atoms | Trusted | TODOs | Verify | Health |",
        "|--------|------:|--------:|------:|:------:|------:|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['path']}` | {r['atoms']} | {r['trusted']} | "
            f"{r['todos']} | {r['verified']} | {r['health']:.3f} |",
        )
    lines.append("")
    lines.append(
        "> Health = `(atoms - trusted) / atoms` − TODO penalty (1% per TODO, "
        "capped 20%). Failing verification halves the score.",
    )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--std-dir",
        type=Path,
        default=REPO_ROOT / "std",
        help="Root of the std/ directory to scan.",
    )
    parser.add_argument(
        "--mumei-bin",
        type=Path,
        default=None,
        help="Path to the mumei binary. If omitted, verification is skipped.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "docs" / "STDLIB_METRICS.md",
        help="Destination markdown file.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing to --output.",
    )
    args = parser.parse_args(argv)

    mumei_bin = args.mumei_bin
    if mumei_bin is not None and not mumei_bin.exists():
        print(f"warning: mumei binary {mumei_bin} not found, skipping verify",
              file=sys.stderr)
        mumei_bin = None

    rows = _scan_std(args.std_dir, mumei_bin)
    markdown = _render_markdown(rows)

    if args.stdout:
        sys.stdout.write(markdown)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")
    print(f"wrote {args.output} ({len(rows)} modules)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
