"""Generate ``docs/STDLIB_METRICS.md`` from the live state of ``std/``.

SI-5 Phase 3-A (mumei-side completion). For each ``std/*.mm`` file we
compute:

* ``atoms``         — total atom definitions declared in the file
* ``trusted``       — number of ``trusted atom`` declarations. These
  are explicit, reviewed contracts (typically wrapping FFI-backed
  runtime calls or quantified predicates Z3 cannot yet discharge), not
  unproven proof holes — see :data:`TRUSTED_CREDIT`.
* ``verified``      — whether ``mumei verify`` succeeds (``OK`` / ``FAIL``
  / ``SKIP`` when no mumei binary is available)
* ``todos``         — count of ``TODO`` / ``FIXME`` / ``XXX`` / ``HACK``
  markers in the file
* ``health_score``  — ``(proven + TRUSTED_CREDIT × trusted) / atoms``
  where ``proven = atoms − trusted`` and ``TRUSTED_CREDIT`` defaults to 0.8
  unless overridden by ``MUMEI_TRUSTED_CREDIT``.
  A TODO penalty of 1% per TODO (capped at 20%) is then subtracted
  and FAIL verification halves the final score. Files without atoms
  score 1.0.

The resulting table is regenerated by ``.github/workflows/update-metrics.yml``
whenever ``std/**`` changes.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

ATOM_RE = re.compile(r"^\s*(?:trusted\s+|async\s+)?atom\s+\w+")
TRUSTED_ATOM_RE = re.compile(r"^\s*trusted\s+atom\s+\w+")
TODO_RE = re.compile(r"//.*?\b(TODO|FIXME|XXX|HACK)\b", re.IGNORECASE)


def _count_metrics(path: Path) -> tuple[int, int, int]:
    """Return ``(atoms, trusted_atoms, todos)`` for ``path``."""
    atoms = trusted = todos = 0
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return 0, 0, 0
    for line in text.splitlines():
        if ATOM_RE.match(line):
            atoms += 1
        if TRUSTED_ATOM_RE.match(line):
            trusted += 1
        if TODO_RE.search(line):
            todos += 1
    return atoms, trusted, todos


def _run_verify(mumei_bin: Path | None, mm_path: Path) -> str:
    """Return ``OK`` / ``FAIL`` / ``SKIP`` for ``mumei verify <mm_path>``."""
    if mumei_bin is None:
        return "SKIP"
    try:
        proc = subprocess.run(  # noqa: S603 — binary path is caller-provided
            [str(mumei_bin), "verify", str(mm_path)],
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return "SKIP"
    return "OK" if proc.returncode == 0 else "FAIL"


#: Credit awarded to ``trusted atom`` declarations. Trusted atoms are
#: explicit, reviewed contracts — typically wrapping FFI-backed runtime
#: calls or quantified predicates that Z3 cannot yet discharge. They are
#: not the same as an unproven atom; the author has vouched for the
#: contract in code review. We therefore award configurable partial credit
#: instead of treating them as proof holes.
TRUSTED_CREDIT = float(os.environ.get("MUMEI_TRUSTED_CREDIT", "0.8"))


def _compute_health(atoms: int, trusted: int, todos: int, verified: str) -> float:
    if atoms == 0:
        base = 1.0
    else:
        proven = atoms - trusted
        base = max(0.0, (proven + TRUSTED_CREDIT * trusted) / atoms)
    penalty = min(todos * 0.01, 0.2)
    score = base - penalty
    if verified == "FAIL":
        # Failing verification halves the score — a module whose Z3 proofs
        # don't close is fundamentally untrustworthy.
        score *= 0.5
    return round(max(0.0, min(1.0, score)), 3)


def _scan_std(std_dir: Path, mumei_bin: Path | None) -> list[dict]:
    rows: list[dict] = []
    for mm_path in sorted(std_dir.rglob("*.mm")):
        rel = str(mm_path.relative_to(std_dir.parent)).replace("\\", "/")
        atoms, trusted, todos = _count_metrics(mm_path)
        verified = _run_verify(mumei_bin, mm_path)
        rows.append(
            {
                "path": rel,
                "atoms": atoms,
                "trusted": trusted,
                "todos": todos,
                "verified": verified,
                "health": _compute_health(atoms, trusted, todos, verified),
            },
        )
    return rows


def _parse_summary(md_text: str, date: str) -> dict | None:
    """Extract Summary numeric fields from a ``STDLIB_METRICS.md`` snapshot.

    Returns ``None`` if required fields (atoms total and weighted health)
    cannot be located — e.g. when the file predates the current layout.
    """
    atoms_m = re.search(
        r"Atoms total:\*\*\s*(\d+)\s*\((\d+)\s*proven\s*[·\u00b7]\s*(\d+)\s*trusted\)",
        md_text,
    )
    health_m = re.search(r"Weighted health score:\*\*\s*([\d.]+)", md_text)
    modules_m = re.search(r"Modules:\*\*\s*(\d+)", md_text)
    todos_m = re.search(r"TODO/FIXME/XXX/HACK markers:\*\*\s*(\d+)", md_text)
    if not atoms_m or not health_m:
        return None
    return {
        "date": date,
        "modules": int(modules_m.group(1)) if modules_m else 0,
        "atoms": int(atoms_m.group(1)),
        "proven": int(atoms_m.group(2)),
        "trusted": int(atoms_m.group(3)),
        "todos": int(todos_m.group(1)) if todos_m else 0,
        "health": float(health_m.group(1)),
    }


def _collect_history(
    repo_root: Path,
    metrics_file: str = "docs/STDLIB_METRICS.md",
    max_entries: int = 20,
) -> list[dict]:
    """Collect past Summary values from ``metrics_file`` via ``git log``.

    Walks the commit history of ``metrics_file`` and parses the Summary
    section of each snapshot. Same-date entries are collapsed to the most
    recent commit and the result is sorted in descending date order,
    limited to ``max_entries`` rows.
    """
    log = subprocess.run(  # noqa: S603,S607 — static args, trusted cwd
        ["git", "log", "--format=%H %ad", "--date=short", "--", metrics_file],
        capture_output=True,
        text=True,
        cwd=repo_root,
        check=False,
    )
    if log.returncode != 0:
        return []

    seen_dates: set[str] = set()
    history: list[dict] = []
    for line in log.stdout.splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) < 2:
            continue
        sha, date = parts[0], parts[1].strip()
        # `git log` already returns newest-first, so the first commit for
        # a given date is the most recent — skip older same-date ones.
        if date in seen_dates:
            continue

        show = subprocess.run(  # noqa: S603,S607
            ["git", "show", f"{sha}:{metrics_file}"],
            capture_output=True,
            text=True,
            cwd=repo_root,
            check=False,
        )
        if show.returncode != 0:
            continue

        entry = _parse_summary(show.stdout, date)
        if entry is None:
            continue
        seen_dates.add(date)
        history.append(entry)
        if len(history) >= max_entries:
            break

    history.sort(key=lambda h: h["date"], reverse=True)
    return history


def _render_markdown(rows: list[dict], history: list[dict] | None = None) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_atoms = sum(r["atoms"] for r in rows)
    total_trusted = sum(r["trusted"] for r in rows)
    total_proven = total_atoms - total_trusted
    total_todos = sum(r["todos"] for r in rows)
    trusted_rows = [r for r in rows if r["trusted"] > 0]
    trusted_modules = ", ".join(
        f"`{r['path']}` ({r['trusted']})" for r in trusted_rows
    ) or "none"
    fully_verified = sum(1 for r in rows if r["verified"] == "OK")
    failed = sum(1 for r in rows if r["verified"] == "FAIL")
    skipped = sum(1 for r in rows if r["verified"] == "SKIP")
    # Weighted health: atoms as weights.
    weighted_health = (
        round(
            sum(r["health"] * max(1, r["atoms"]) for r in rows)
            / max(1, sum(max(1, r["atoms"]) for r in rows)),
            3,
        )
    )

    lines = [
        "# Mumei std/ Metrics",
        "",
        f"_Auto-generated by `scripts/generate_stdlib_metrics.py` — {generated_at}_",
        "",
        "Part of **SI-5 Phase 3-A**. Measures the health of the verified",
        "standard library by counting atoms, trusted atoms (reviewed contracts),",
        "TODO markers and the result of `mumei verify` per module. The CI",
        "workflow `.github/workflows/update-metrics.yml` keeps this file",
        "fresh on every push to `std/`.",
        "",
        "## Summary",
        "",
        f"- **Modules:** {len(rows)} ({fully_verified} OK / {failed} FAIL / {skipped} SKIP)",
        f"- **Atoms total:** {total_atoms} ({total_proven} proven · {total_trusted} trusted)",
        f"- **Trusted atoms (reviewed contracts):** {total_trusted}",
        f"- **Trusted atom modules:** {trusted_modules}",
        f"- **TODO/FIXME/XXX/HACK markers:** {total_todos}",
        f"- **Weighted health score:** {weighted_health:.3f} / 1.000",
        "",
        "## Trusted atom inventory",
        "",
    ]
    if trusted_rows:
        lines.extend(
            [
                "| Module | Trusted atoms | Health |",
                "|--------|--------------:|------:|",
            ]
        )
        for r in trusted_rows:
            lines.append(f"| `{r['path']}` | {r['trusted']} | {r['health']:.3f} |")
    else:
        lines.append("_No trusted atoms remain in std/._")
    lines.extend([
        "",
        "## Per-module breakdown",
        "",
        "| Module | Atoms | Trusted | TODOs | Verify | Health |",
        "|--------|------:|--------:|------:|:------:|------:|",
    ])
    for r in rows:
        lines.append(
            f"| `{r['path']}` | {r['atoms']} | {r['trusted']} | "
            f"{r['todos']} | {r['verified']} | {r['health']:.3f} |",
        )
    lines.append("")
    lines.append(
        f"> Health = `(proven + {TRUSTED_CREDIT:g} × trusted) / atoms` − TODO penalty "
        "(1% per TODO, capped 20%). Failing verification halves the score. "
        f"Trusted atoms receive {TRUSTED_CREDIT:g} credit because they are explicit, reviewed "
        "contracts (typically FFI-backed or quantified predicates beyond Z3's "
        "current reach), not unproven proof holes.",
    )
    lines.append("")

    lines.append("## History")
    lines.append("")
    if history:
        lines.append(
            "| Date | Modules | Atoms | Proven | Trusted | TODOs | Health |",
        )
        lines.append(
            "|------|--------:|------:|-------:|--------:|------:|-------:|",
        )
        for h in history:
            lines.append(
                f"| {h['date']} | {h['modules']} | {h['atoms']} | "
                f"{h['proven']} | {h['trusted']} | {h['todos']} | "
                f"{h['health']:.3f} |",
            )
    else:
        lines.append("_No history available._")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--std-dir",
        type=Path,
        default=REPO_ROOT / "std",
        help="Root of the std/ directory to scan.",
    )
    parser.add_argument(
        "--mumei-bin",
        type=Path,
        default=None,
        help="Path to the mumei binary. If omitted, verification is skipped.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "docs" / "STDLIB_METRICS.md",
        help="Destination markdown file.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing to --output.",
    )
    parser.add_argument(
        "--no-history",
        action="store_true",
        help="Skip git history collection (faster for local runs).",
    )
    args = parser.parse_args(argv)

    mumei_bin = args.mumei_bin
    if mumei_bin is not None and not mumei_bin.exists():
        print(f"warning: mumei binary {mumei_bin} not found, skipping verify",
              file=sys.stderr)
        mumei_bin = None

    rows = _scan_std(args.std_dir, mumei_bin)
    history: list[dict] = []
    if not args.stdout and not args.no_history:
        history = _collect_history(REPO_ROOT)
    markdown = _render_markdown(rows, history)

    if args.stdout:
        sys.stdout.write(markdown)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")
    print(f"wrote {args.output} ({len(rows)} modules)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
