"""Generate std/ dependency graph visualization (SI-5 Phase 1-C).

Re-uses the helpers exposed by ``mcp_server.py`` so the output is exactly
what the ``visualize_std_graph`` MCP tool returns. Intended to be run from
CI (``proliferate.yml``, ``update-metrics.yml``, etc.) to keep a committed
Mermaid rendering in sync with the live dependency graph.

Usage:
    python visualizer/generate_graph.py [--format mermaid|dot] \
        [--output visualizer/std_graph.md]

Defaults to ``mermaid`` written to ``visualizer/std_graph.md`` so the
diagram renders natively on GitHub.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Expose mcp_server on sys.path so running this script in isolation works.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Lazy-import helpers from mcp_server to avoid triggering FastMCP
# initialisation (and requiring the `mcp` package) at module scope.
# The actual import happens inside generate() where the helpers are needed.
_mcp_helpers = None


def _get_helpers():
    """Lazy-import graph helpers from mcp_server.

    Deferred so that ``from mcp_server import …`` (which executes
    ``mcp = FastMCP(…)`` at module scope) only runs when the helpers
    are actually needed — not at import time of *this* module.  This
    lets CI environments that lack the ``mcp`` package still import
    ``generate_graph`` for testing without an immediate ImportError.
    """
    global _mcp_helpers
    if _mcp_helpers is not None:
        return _mcp_helpers
    try:
        from mcp_server import (  # noqa: E402
            _collect_trusted_atoms,
            _count_atoms_per_file,
            _render_std_graph_dot,
            _render_std_graph_mermaid,
            _scan_std_imports,
            _trusted_by_file_counts,
        )
    except ImportError as exc:
        raise ImportError(
            "Failed to import mcp_server helpers. "
            "Ensure the `mcp` package is installed "
            "(pip install -r requirements-mcp.txt)."
        ) from exc
    _mcp_helpers = {
        "scan_std_imports": _scan_std_imports,
        "collect_trusted_atoms": _collect_trusted_atoms,
        "trusted_by_file_counts": _trusted_by_file_counts,
        "count_atoms_per_file": _count_atoms_per_file,
        "render_mermaid": _render_std_graph_mermaid,
        "render_dot": _render_std_graph_dot,
    }
    return _mcp_helpers


def _build_markdown(mermaid_source: str) -> str:
    """Wrap Mermaid source in a README-friendly markdown document."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        "# std/ Dependency Graph\n\n"
        f"_Generated: {generated_at}_\n\n"
        "This document is generated by `visualizer/generate_graph.py` from "
        "the output of the `visualize_std_graph` MCP tool. It renders "
        "natively on GitHub.\n\n"
        "- **Green** (rounded): fully verified — no `trusted atom`.\n"
        "- **Yellow** (hexagon): verified, but at least one `trusted atom` "
        "(proof hole) is present.\n"
        "- **Red** (double border): verification failed or module missing "
        "(reserved for CI augmentation).\n\n"
        "Each node label carries `<path>\\n<N> atoms, <M> trusted` so the "
        "density of proof holes is visible at a glance.\n\n"
        "```mermaid\n"
        f"{mermaid_source.rstrip()}\n"
        "```\n"
    )


def generate(
    fmt: str,
    std_dir: Path | None = None,
) -> str:
    """Render the std/ dependency graph in ``fmt`` (``mermaid`` or ``dot``)."""
    if std_dir is None:
        std_dir = REPO_ROOT / "std"
    if not std_dir.exists():
        raise FileNotFoundError(f"std directory not found: {std_dir}")

    h = _get_helpers()
    dependency_graph = h["scan_std_imports"](std_dir)
    trusted_atoms = h["collect_trusted_atoms"](std_dir)
    trusted_by_file = h["trusted_by_file_counts"](trusted_atoms)
    atoms_by_file = h["count_atoms_per_file"](std_dir)
    failed_files: set = set()

    if fmt == "mermaid":
        return h["render_mermaid"](
            dependency_graph,
            trusted_by_file,
            atoms_by_file,
            failed_files,
        )
    if fmt == "dot":
        return h["render_dot"](
            dependency_graph,
            trusted_by_file,
            atoms_by_file,
            failed_files,
        )
    raise ValueError(f"unsupported format {fmt!r}; expected mermaid or dot")


def _default_output(fmt: str) -> Path:
    if fmt == "mermaid":
        return REPO_ROOT / "visualizer" / "std_graph.md"
    return REPO_ROOT / "visualizer" / "std_graph.dot"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--format",
        choices=["mermaid", "dot"],
        default="mermaid",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output file path (default depends on --format).",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the graph source to stdout instead of writing a file.",
    )
    args = parser.parse_args(argv)

    source = generate(args.format)
    if args.format == "mermaid":
        payload = _build_markdown(source)
    else:
        payload = source

    if args.stdout:
        sys.stdout.write(payload)
        return 0

    output = args.output or _default_output(args.format)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(payload, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":  # pragma: no cover - thin CLI wrapper
    raise SystemExit(main())
