"""Generate std/ dependency graph visualization (SI-5 Phase 1-C).

Re-uses the pure helpers exposed by :mod:`std_graph_lib` so the output is
exactly what the ``visualize_std_graph`` MCP tool returns. Intended to be
run from CI (``proliferate.yml``, ``update-metrics.yml``, etc.) to keep a
committed Mermaid rendering in sync with the live dependency graph.

Usage:
    python visualizer/generate_graph.py [--format mermaid|dot] \
        [--output visualizer/std_graph.md]

Defaults to ``mermaid`` written to ``visualizer/std_graph.md`` so the
diagram renders natively on GitHub.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Expose std_graph_lib on sys.path so running this script in isolation
# (e.g. `python visualizer/generate_graph.py`) works from any CWD.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# ws5 / SI-5 Phase 1-C follow-up: import the pure-Python graph helpers
# directly from std_graph_lib — no more lazy FastMCP import dance.
from std_graph_lib import (  # noqa: E402
    collect_trusted_atoms,
    count_atoms_per_file,
    render_std_graph_dot,
    render_std_graph_mermaid,
    scan_std_imports,
    trusted_by_file_counts,
)


def _build_markdown(mermaid_source: str) -> str:
    """Wrap Mermaid source in a README-friendly markdown document."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        "# std/ Dependency Graph\n\n"
        f"_Generated: {generated_at}_\n\n"
        "This document is generated by `visualizer/generate_graph.py` from "
        "the output of the `visualize_std_graph` MCP tool. It renders "
        "natively on GitHub.\n\n"
        "- **Green** (rounded): fully verified — no `trusted atom`.\n"
        "- **Yellow** (hexagon): verified, but at least one `trusted atom` "
        "(proof hole) is present.\n"
        "- **Red** (double border): verification failed or module missing "
        "(reserved for CI augmentation).\n\n"
        "Each node label carries `<path>\\n<N> atoms, <M> trusted` so the "
        "density of proof holes is visible at a glance.\n\n"
        "```mermaid\n"
        f"{mermaid_source.rstrip()}\n"
        "```\n"
    )


def generate(
    fmt: str,
    std_dir: Path | None = None,
) -> str:
    """Render the std/ dependency graph in ``fmt`` (``mermaid`` or ``dot``)."""
    if std_dir is None:
        std_dir = REPO_ROOT / "std"
    if not std_dir.exists():
        raise FileNotFoundError(f"std directory not found: {std_dir}")

    dependency_graph = scan_std_imports(std_dir)
    trusted_atoms = collect_trusted_atoms(std_dir)
    trusted_by_file = trusted_by_file_counts(trusted_atoms)
    atoms_by_file = count_atoms_per_file(std_dir)
    failed_files: set = set()

    if fmt == "mermaid":
        return render_std_graph_mermaid(
            dependency_graph,
            trusted_by_file,
            atoms_by_file,
            failed_files,
        )
    if fmt == "dot":
        return render_std_graph_dot(
            dependency_graph,
            trusted_by_file,
            atoms_by_file,
            failed_files,
        )
    raise ValueError(f"unsupported format {fmt!r}; expected mermaid or dot")


def _default_output(fmt: str) -> Path:
    if fmt == "mermaid":
        return REPO_ROOT / "visualizer" / "std_graph.md"
    return REPO_ROOT / "visualizer" / "std_graph.dot"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--format",
        choices=["mermaid", "dot"],
        default="mermaid",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output file path (default depends on --format).",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the graph source to stdout instead of writing a file.",
    )
    args = parser.parse_args(argv)

    source = generate(args.format)
    if args.format == "mermaid":
        payload = _build_markdown(source)
    else:
        payload = source

    if args.stdout:
        sys.stdout.write(payload)
        return 0

    output = args.output or _default_output(args.format)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(payload, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":  # pragma: no cover - thin CLI wrapper
    raise SystemExit(main())
